server:
  port: 9527
spring:
  application:
    name: framework-zuul
#Eureka的配置，服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: framework-zuul-9527 #修改eureka上的默认描述信息
    prefer-ip-address: true #显示IP地址
#info配置
info:
  app.name: com.trkj.framework
  company.name: blog.trkj
#路由配置
zuul:
  routes:
    one.serviceId: register-8001 #原来的地址
    one.path: /8001/** #现在的地址
    two.serviceId: register-8002 #原来的地址
    two.path: /8002/** #现在的地址
    three.serviceId: register-8003 #原来的地址
    three.path: /8003/** #现在的地址
    four.serviceId: register-8004 #原来的地址
    four.path: /8004/** #现在的地址
    five.serviceId: register-8005 #原来的地址
    five.path: /8005/** #现在的地址
    six.serviceId: register-8006 #原来的地址
    six.path: /8006/** #现在的地址
    seven.serviceId: register-8007 #原来的地址
    seven.path: /8007/** #现在的地址
    eight.serviceId: register-8008 #原来的地址
    eight.path: /8008/** #现在的地址
    nine.serviceId: register-8009 #原来的地址
    nine.path: /8009/** #现在的地址
    ten.serviceId: register-8010 #原来的地址
    ten.path: /8010/** #现在的地址
    eleven.serviceId: register-8011 #原来的地址
    eleven.path: /8011/** #现在的地址
  ignored-services: "*" #不能再使用这个路径访问，ignored：忽略 ,隐藏全部的~
  host:
    connect-timeout-millis: 3000
    socket-timeout-millis: 3000
  sensitive-headers: "*"

# 添加ribbon的超时时间设置
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000

# JWT配置
jwt:
  # 密匙KEY
  secret: JwtSecret
  # HeaderKEY
  header: JWTDemo
  # 过期时间(这里设定为豪秒)
  expire: 60000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeout-in-milliseconds: 3000
