server:
  port: 9527
spring:
  application:
    name: framework-zuul
#Eureka的配置，服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: framework-zuul-9527 #修改eureka上的默认描述信息
    prefer-ip-address: true #显示IP地址
#info配置
info:
  app.name: com.trkj.framework
  company.name: blog.trkj
#路由配置
zuul:
  routes:
    mydept.serviceId: register-8001 #原来的地址
    mydept.path: /** #现在的地址
  ignored-services: "*" #不能再使用这个路径访问，ignored：忽略 ,隐藏全部的~