ALTER SYSTEM SET DEFERRED_SEGMENT_CREATION=FALSE;
-- 创建角色表
CREATE TABLE ROLE(
   ROLE_ID NUMBER(10) PRIMARY KEY   NOT NULL,-- 角色编号
	 ROLE_NAME VARCHAR2(20)  NOT NULL ,--角色名称 
   ROLE_STATE NUMBER(2) DEFAULT  0 CHECK (ROLE_STATE IN (0,1)) NOT NULL ,-- 角色状态 0:启用 1:禁用
   ROLE_DESCRIBE VARCHAR2(200),-- 角色描述
   CREATED_TIME DATE NOT NULL,-- 创建时间
   UPDATED_TIME DATE NOT NULL,-- 修改时间
   REVISION NUMBER(10) DEFAULT  1 NOT NULL,-- 乐观锁
	 IS_DELETED NUMBER(10) DEFAULT 0 CHECK(IS_DELETED IN(0,1))-- 逻辑删除 0:未删 1:已删
);


COMMENT ON TABLE ROLE IS '角色表';
COMMENT ON COLUMN ROLE.ROLE_ID IS '角色编号';
COMMENT ON COLUMN ROLE.ROLE_NAME IS '角色名称';
COMMENT ON COLUMN ROLE.ROLE_STATE IS '角色状态 0:启用 1:禁用';
COMMENT ON COLUMN ROLE.ROLE_DESCRIBE IS '角色描述';
COMMENT ON COLUMN ROLE.CREATED_TIME IS '创建时间';
COMMENT ON COLUMN ROLE.UPDATED_TIME IS '修改时间';
COMMENT ON COLUMN ROLE.REVISION IS '乐观锁';
COMMENT ON COLUMN ROLE.IS_DELETED IS '逻辑删除 0:未删 1:已删 ';


/*创建自增序列*/
CREATE SEQUENCE ROLE_ID
--最小值
MINVALUE 1
--不设置最大值
NOMAXVALUE
--从1开始计数
START WITH 1
--每次加1
INCREMENT BY 1
--一直累加，不循环
NOCYCLE
--不建缓冲区
NOCACHE;


--创建菜单权限表
CREATE TABLE MENU_POWER(
MENU_POWER_ID NUMBER(10) PRIMARY KEY   NOT NULL,--菜单权限编号
MENU_POWER_PID NUMBER(10) NOT NULL,--父级菜单权限编号
MENU_POWER_ORDER NUMBER(10) NOT NULL ,--显示顺序
MENU_POWER_LEAF NUMBER(10) DEFAULT 0 CHECK (MENU_POWER_LEAF IN (0,1)) NOT NULL ,--是否有叶子 0:有 1:没有
MENU_POWER_TYPE NUMBER(10) DEFAULT 0 CHECK (MENU_POWER_TYPE IN (0,1)) NOT NULL,--菜单权限类型 0:目录 1:菜单 2:按钮
MENU_POWER_STATE NUMBER(10) DEFAULT 0 CHECK (MENU_POWER_STATE IN (0,1)) NOT NULL,--菜单权限类型 0启用 1:禁用
MENU_POWER_NAME VARCHAR2(50)  NOT NULL,--菜单权限名称
MENU_POWER_ROUTE VARCHAR2(100) ,--路由地址
PICTURE_ADDRESS VARCHAR2(100)  ,--图片地址
MENU_POWER_MODULE VARCHAR2(100) ,--组件地址
CREATED_TIME DATE NOT NULL,-- 创建时间 精确到秒
UPDATED_TIME DATE NOT NULL,-- 修改时间 精确到秒
REVISION NUMBER(10) DEFAULT  1 NOT NULL-- 乐观锁
); 



COMMENT ON TABLE MENU_POWER IS '菜单权限表';
COMMENT ON COLUMN MENU_POWER.MENU_POWER_ID IS '菜单权限编号';
COMMENT ON COLUMN MENU_POWER.MENU_POWER_PID IS '父级菜单权限编号';
COMMENT ON COLUMN MENU_POWER.MENU_POWER_ORDER IS '显示顺序';
COMMENT ON COLUMN MENU_POWER.MENU_POWER_LEAF IS '是否有叶子 0:有 1:没有';
COMMENT ON COLUMN MENU_POWER.MENU_POWER_TYPE IS '菜单权限类型 0:目录 1:菜单 2:按钮';
COMMENT ON COLUMN MENU_POWER.MENU_POWER_STATE IS '菜单权限类型 0启用 1:禁用';
COMMENT ON COLUMN MENU_POWER.MENU_POWER_NAME IS '菜单权限名称';
COMMENT ON COLUMN MENU_POWER.MENU_POWER_ROUTE IS '路由地址';
COMMENT ON COLUMN MENU_POWER.MENU_POWER_MODULE IS '组件地址';
COMMENT ON COLUMN MENU_POWER.CREATED_TIME IS '创建时间 精确到秒';
COMMENT ON COLUMN MENU_POWER.UPDATED_TIME IS '修改时间 精确到秒';
COMMENT ON COLUMN MENU_POWER.REVISION IS '乐观锁';

 --drop SEQUENCE MENU_POWER_ID;

/*创建自增序列*/
CREATE SEQUENCE MENU_POWER_ID
--最小值
MINVALUE 1
--不设置最大值
NOMAXVALUE
--从1开始计数
START WITH 1
--每次加1
INCREMENT BY 1
--一直累加，不循环
NOCYCLE
--不建缓冲区
NOCACHE;


--创建角色菜单权限表
CREATE TABLE ROLE_MENU_POWER(
ROLE_MENU_POWER_ID NUMBER(10) PRIMARY KEY   NOT NULL,--角色菜单权限编号
ROLE_ID NUMBER(10) NOT NULL , --角色编号
MENU_POWER_ID NUMBER(10) NOT NULL ,--菜单权限编号
CREATED_TIME DATE NOT NULL,-- 创建时间 精确到秒
UPDATED_TIME DATE NOT NULL,-- 修改时间 精确到秒
REVISION NUMBER(10) DEFAULT  1 NOT NULL,-- 乐观锁
IS_CHOICE NUMBER(10) DEFAULT 0 CHECK(IS_CHOICE IN(0,1))-- 是否半选择 0:否 1:是
);


COMMENT ON TABLE ROLE_MENU_POWER IS '角色菜单权限表';
COMMENT ON COLUMN ROLE_MENU_POWER.ROLE_MENU_POWER_ID IS '角色菜单权限编号';
COMMENT ON COLUMN ROLE_MENU_POWER.ROLE_ID IS '角色编号';
COMMENT ON COLUMN ROLE_MENU_POWER.MENU_POWER_ID IS '菜单权限编号';
COMMENT ON COLUMN ROLE_MENU_POWER.CREATED_TIME IS '创建时间 精确到秒';
COMMENT ON COLUMN ROLE_MENU_POWER.UPDATED_TIME IS '修改时间 精确到秒';
COMMENT ON COLUMN ROLE_MENU_POWER.REVISION IS '乐观锁';
COMMENT ON COLUMN ROLE_MENU_POWER.IS_CHOICE IS '是否半选择 0:否 1:是';

-- drop SEQUENCE ROLE_MENU_POWER_ID;

/*创建自增序列*/
CREATE SEQUENCE ROLE_MENU_POWER_ID
--最小值
MINVALUE 1
--不设置最大值
NOMAXVALUE
--从1开始计数
START WITH 1
--每次加1
INCREMENT BY 1
--一直累加，不循环
NOCYCLE
--不建缓冲区
NOCACHE;


--创建角色员工表
CREATE TABLE ROLE_STAFF(
ROLE_STAFF_ID NUMBER(10) PRIMARY KEY   NOT NULL,--角色员工编号
ROLE_ID NUMBER(10) NOT NULL,--角色编号
STAFF_ID NUMBER(10) NOT NULL,--员工编号
CREATED_TIME DATE NOT NULL,-- 创建时间 精确到秒
UPDATED_TIME DATE NOT NULL,-- 修改时间 精确到秒
REVISION NUMBER(10) DEFAULT  1 NOT NULL-- 乐观锁
);


COMMENT ON TABLE ROLE_STAFF IS '角色员工表';
COMMENT ON COLUMN ROLE_STAFF.ROLE_STAFF_ID IS '角色员工编号';
COMMENT ON COLUMN ROLE_STAFF.ROLE_ID IS '角色编号';
COMMENT ON COLUMN ROLE_STAFF.STAFF_ID IS '员工编号';
COMMENT ON COLUMN ROLE_STAFF.CREATED_TIME IS '创建时间 精确到秒';
COMMENT ON COLUMN ROLE_STAFF.UPDATED_TIME IS '修改时间 精确到秒';
COMMENT ON COLUMN ROLE_STAFF.REVISION IS '乐观锁';


/*创建自增序列*/
CREATE SEQUENCE ROLE_STAFF_ID
--最小值
MINVALUE 1
--不设置最大值
NOMAXVALUE
--从1开始计数
START WITH 1
--每次加1
INCREMENT BY 1
--一直累加，不循环
NOCYCLE
--不建缓冲区
NOCACHE;


--创建公告表
CREATE TABLE NOTICE(
NOTICE_ID NUMBER(10) PRIMARY KEY   NOT NULL,--公告编号
STAFF_ID NUMBER(10) NOT NULL,--员工编号
NOTICE_TYPE NUMBER(10) DEFAULT 0 CHECK (NOTICE_TYPE IN(0,1,2)) NOT NULL,--公告类型 0:增发 1:一般公告	 2:重大事项
NOTICE_TITLE VARCHAR2(50) NOT NULL,--公告标题
NOTICE_STATE NUMBER(10) DEFAULT 0 CHECK(NOTICE_STATE IN(0,1)),--公告状态 0:启用 1:禁用
NOTICE_PEOPLE VARCHAR2(20) NOT NULL,--发布人
NOTICE_POST VARCHAR2(20) NOT NULL,--职位
NOTICE_MATTER VARCHAR2(1000) NOT NULL,--发布内容
CREATED_TIME DATE NOT NULL,-- 创建时间 精确到秒
UPDATED_TIME DATE NOT NULL,-- 修改时间 精确到秒
REVISION NUMBER(10) DEFAULT  1 NOT NULL,-- 乐观锁	
IS_DELETED NUMBER(10) DEFAULT 0 CHECK(IS_DELETED IN(0,1))-- 逻辑删除 0:未删 1:已删
);



COMMENT ON TABLE NOTICE IS '公告表';
COMMENT ON COLUMN NOTICE.NOTICE_ID IS '公告编号';
COMMENT ON COLUMN NOTICE.STAFF_ID IS '员工编号';
COMMENT ON COLUMN NOTICE.NOTICE_TYPE IS '公告类型 0:要事性 1:政策性 2:任免性';
COMMENT ON COLUMN NOTICE.NOTICE_TITLE IS '公告标题';
COMMENT ON COLUMN NOTICE.NOTICE_STATE IS '公告状态 0:启用 1:禁用';
COMMENT ON COLUMN NOTICE.NOTICE_PEOPLE IS '发布人';
COMMENT ON COLUMN NOTICE.NOTICE_POST IS '职位';
COMMENT ON COLUMN NOTICE.NOTICE_MATTER IS '发布内容';
COMMENT ON COLUMN NOTICE.CREATED_TIME IS '创建时间 精确到秒';
COMMENT ON COLUMN NOTICE.UPDATED_TIME IS '修改时间 精确到秒';
COMMENT ON COLUMN NOTICE.REVISION IS '乐观锁';
COMMENT ON COLUMN NOTICE.IS_DELETED IS '逻辑删除 0:未删 1:已删 ';


/*创建自增序列*/
CREATE SEQUENCE NOTICE_ID
--最小值
MINVALUE 1
--不设置最大值
NOMAXVALUE
--从1开始计数
START WITH 1
--每次加1
INCREMENT BY 1
--一直累加，不循环
NOCYCLE
--不建缓冲区
NOCACHE;


--创建公告部门表
CREATE TABLE NOTICE_DEPT(
NOTICE_DEPT_ID NUMBER(10) PRIMARY KEY   NOT NULL,--公告部门编号
DEPT_ID NUMBER(10) NOT NULL,--部门编号
NOTICE_ID NUMBER(10) NOT NULL,--公告编号
CREATED_TIME DATE NOT NULL,-- 创建时间 精确到秒
UPDATED_TIME DATE NOT NULL,-- 修改时间 精确到秒
REVISION NUMBER(10) DEFAULT  1 NOT NULL-- 乐观锁
);



COMMENT ON TABLE NOTICE_DEPT IS '公告部门表';
COMMENT ON COLUMN NOTICE_DEPT.NOTICE_DEPT_ID IS '公告部门编号';
COMMENT ON COLUMN NOTICE_DEPT.DEPT_ID IS '部门编号';
COMMENT ON COLUMN NOTICE_DEPT.NOTICE_ID IS '公告编号';
COMMENT ON COLUMN NOTICE_DEPT.CREATED_TIME IS '创建时间 精确到秒';
COMMENT ON COLUMN NOTICE_DEPT.UPDATED_TIME IS '修改时间 精确到秒';
COMMENT ON COLUMN NOTICE_DEPT.REVISION IS '乐观锁';


/*创建自增序列*/
CREATE SEQUENCE NOTICE_DEPT_ID
--最小值
MINVALUE 1
--不设置最大值
NOMAXVALUE
--从1开始计数
START WITH 1
--每次加1
INCREMENT BY 1
--一直累加，不循环
NOCYCLE
--不建缓冲区
NOCACHE;


--创建公告员工表
CREATE TABLE NOTICE_STAFF(
NOTICE_STAFF_ID NUMBER(10) PRIMARY KEY   NOT NULL,--公告员工编号
STAFF_ID NUMBER(10) NOT NULL,--员工编号
NOTICE_ID NUMBER(10) NOT NULL,--公告编号
NOTICE_STATE NUMBER(10) DEFAULT 0 CHECK(NOTICE_STATE IN (0,1)),--公告状态 0:未读 1:已读
CREATED_TIME DATE NOT NULL,-- 创建时间 精确到秒
UPDATED_TIME DATE NOT NULL,-- 修改时间 精确到秒
REVISION NUMBER(10) DEFAULT  1 NOT NULL-- 乐观锁
);



COMMENT ON TABLE NOTICE_STAFF IS '公告员工表';
COMMENT ON COLUMN NOTICE_STAFF.NOTICE_STAFF_ID IS '公告员工编号';
COMMENT ON COLUMN NOTICE_STAFF.STAFF_ID IS '员工编号';
COMMENT ON COLUMN NOTICE_STAFF.NOTICE_ID IS '公告编号';
COMMENT ON COLUMN NOTICE_STAFF.NOTICE_STATE IS '公告状态 0:未读 1:已读';
COMMENT ON COLUMN NOTICE_STAFF.CREATED_TIME IS '创建时间 精确到秒';
COMMENT ON COLUMN NOTICE_STAFF.UPDATED_TIME IS '修改时间 精确到秒';
COMMENT ON COLUMN NOTICE_STAFF.REVISION IS '乐观锁';


/*创建自增序列*/
CREATE SEQUENCE NOTICE_STAFF_ID
--最小值
MINVALUE 1
--不设置最大值
NOMAXVALUE
--从1开始计数
START WITH 1
--每次加1
INCREMENT BY 1
--一直累加，不循环
NOCYCLE
--不建缓冲区
NOCACHE;


--创建消息表
CREATE TABLE NEWS(
NEW_ID NUMBER(10) PRIMARY KEY   NOT NULL,--消息编号
STAFF_ID NUMBER(10) NOT NULL,--员工编号
NEWS_MATTER VARCHAR2(1000) NOT NULL,--消息内容
NEWS_TITLE VARCHAR2(50) NOT NULL ,--消息标题
NEWS_STATE NUMBER(10) DEFAULT 0 CHECK(NEWS_STATE IN (0,1)),--消息状态 0:未读 1:已读
CREATED_TIME DATE NOT NULL,-- 创建时间 精确到秒
UPDATED_TIME DATE NOT NULL,-- 修改时间 精确到秒
REVISION NUMBER(10) DEFAULT  1 NOT NULL,-- 乐观锁
IS_DELETED NUMBER(10) DEFAULT 0 CHECK(IS_DELETED IN(0,1))-- 逻辑删除 0:未删 1:已删
);

COMMENT ON TABLE NEWS IS '消息表';
COMMENT ON COLUMN NEWS.NEW_ID IS '消息编号';
COMMENT ON COLUMN NEWS.STAFF_ID IS '员工编号';
COMMENT ON COLUMN NEWS.NEWS_MATTER IS '消息内容';
COMMENT ON COLUMN NEWS.NEWS_TITLE IS '消息标题';
COMMENT ON COLUMN NEWS.NEWS_STATE IS '消息状态';
COMMENT ON COLUMN NEWS.CREATED_TIME IS '创建时间 精确到秒';
COMMENT ON COLUMN NEWS.UPDATED_TIME IS '修改时间 精确到秒';
COMMENT ON COLUMN NEWS.REVISION IS '乐观锁';
COMMENT ON COLUMN NEWS.IS_DELETED IS '逻辑删除 0:未删 1:已删 ';


/*创建自增序列*/
CREATE SEQUENCE NEWS_ID
--最小值
MINVALUE 1
--不设置最大值
NOMAXVALUE
--从1开始计数
START WITH 1
--每次加1
INCREMENT BY 1
--一直累加，不循环
NOCYCLE
--不建缓冲区
NOCACHE;


--创建登录日志表
CREATE TABLE REGISTER_LOG(
REGISTER_LOG_ID NUMBER(10) PRIMARY KEY   NOT NULL,--登录日志编号
REGISTER_LOG_PEOPLE VARCHAR2(20)  ,-- 员工名称
REGISTER_LOG_PHONE NUMBER(11),--手机号码
REGISTER_LOG_IP VARCHAR2(100) NOT NULL,--IP地址
REGISTER_LOG_IPNAME VARCHAR2(100) NOT NULL,--IP地址所在地
REGISTER_LOG_TYPE VARCHAR2(100) NOT NULL,--设备类型
REGISTER_LOG_STATE NUMBER(10) DEFAULT 0 CHECK(REGISTER_LOG_STATE IN (0,1)), -- 登录状态 0:成功 1:失败
REGISTER_LOG_BROWSER VARCHAR2(100) NOT NULL,-- 浏览器
REGISTER_LOG_GENRE NUMBER DEFAULT 0 CHECK(REGISTER_LOG_GENRE IN (0,1)),--登录类型 0:人脸 1:密码
CREATED_TIME DATE NOT NULL,-- 创建时间 精确到秒
UPDATED_TIME DATE NOT NULL,-- 修改时间 精确到秒
REVISION NUMBER(10) DEFAULT  1 NOT NULL,-- 乐观锁
IS_DELETED NUMBER(10) DEFAULT 0 CHECK(IS_DELETED IN(0,1))-- 逻辑删除 0:未删 1:已删
);


COMMENT ON TABLE REGISTER_LOG IS '登录日志表';
COMMENT ON COLUMN REGISTER_LOG.REGISTER_LOG_ID IS '登录日志编号';
COMMENT ON COLUMN REGISTER_LOG.REGISTER_LOG_PEOPLE IS '员工名称';
COMMENT ON COLUMN REGISTER_LOG.REGISTER_LOG_PHONE IS '手机号码';
COMMENT ON COLUMN REGISTER_LOG.REGISTER_LOG_IP IS 'IP地址';
COMMENT ON COLUMN REGISTER_LOG.REGISTER_LOG_IPNAME IS 'IP所在地';
COMMENT ON COLUMN REGISTER_LOG.REGISTER_LOG_TYPE IS '设备类型';
COMMENT ON COLUMN REGISTER_LOG.REGISTER_LOG_STATE IS '登录状态 0:成功 1:失败';
COMMENT ON COLUMN REGISTER_LOG.REGISTER_LOG_BROWSER IS '浏览器';
COMMENT ON COLUMN REGISTER_LOG.REGISTER_LOG_GENRE IS '登录类型 0:人脸 1:密码';
COMMENT ON COLUMN REGISTER_LOG.CREATED_TIME IS '创建时间 精确到秒';
COMMENT ON COLUMN REGISTER_LOG.UPDATED_TIME IS '修改时间 精确到秒';
COMMENT ON COLUMN REGISTER_LOG.REVISION IS '乐观锁';
COMMENT ON COLUMN REGISTER_LOG.IS_DELETED IS '逻辑删除 0:未删 1:已删';

/*创建自增序列*/
CREATE SEQUENCE REGISTER_LOG_ID
--最小值
MINVALUE 1
--不设置最大值
NOMAXVALUE
--从1开始计数
START WITH 1
--每次加1
INCREMENT BY 1
--一直累加，不循环
NOCYCLE
--不建缓冲区
NOCACHE;

--创建操作日志表
CREATE TABLE OPERAT_LOG(
OPERAT_LOG_ID NUMBER(10) PRIMARY KEY   NOT NULL,--操作日志编号
STAFF_ID NUMBER(10) NOT NULL,--员工编号
OPERAT_LOG_MODULE VARCHAR2(100) NOT NULL,--系统模块
OPERAT_LOG_TYPE VARCHAR2(20) NOT NULL,--操作类型
OPERAT_LOG_PEOPLE VARCHAR2(20) NOT NULL,--员工名称
OPERAT_LOG_POST VARCHAR2(20) NOT NULL,--员工职位
OPERAT_LOG_REQUEST VARCHAR2(20) NOT NULL,--请求方式
OPERAT_LOG_URL varchar2(1000) NOT NULL,--请求地址
OPERAT_LOG_METHOD varchar2(1000) NOT NULL,--请求方法
OPERAT_LOG_REQUEST_PARAMETER varchar2(1000) ,--请求参数
OPERAT_LOG_RETURN_PARAMETERS varchar2(1000) ,--返回参数
OPERAT_LOG_CONTENT varchar2(1000),--操作内容
CREATED_TIME DATE NOT NULL,-- 创建时间 精确到秒
UPDATED_TIME DATE NOT NULL,-- 修改时间 精确到秒
REVISION NUMBER(10) DEFAULT  1 NOT NULL,-- 乐观锁
IS_DELETED NUMBER(10) DEFAULT 0 CHECK(IS_DELETED IN(0,1))-- 逻辑删除 0:未删 1:已删
);

COMMENT ON TABLE OPERAT_LOG IS '操作日志表';
COMMENT ON COLUMN OPERAT_LOG.OPERAT_LOG_ID IS '操作日志编号';
COMMENT ON COLUMN OPERAT_LOG.STAFF_ID IS '员工编号';
COMMENT ON COLUMN OPERAT_LOG.OPERAT_LOG_MODULE IS '系统模块';
COMMENT ON COLUMN OPERAT_LOG.OPERAT_LOG_TYPE IS '操作类型';
COMMENT ON COLUMN OPERAT_LOG.OPERAT_LOG_PEOPLE IS '员工名称';
COMMENT ON COLUMN OPERAT_LOG.OPERAT_LOG_POST IS '员工职位';
COMMENT ON COLUMN OPERAT_LOG.OPERAT_LOG_REQUEST IS '请求方式';
COMMENT ON COLUMN OPERAT_LOG.OPERAT_LOG_URL IS '请求地址';
COMMENT ON COLUMN OPERAT_LOG.OPERAT_LOG_METHOD IS '请求方法';
COMMENT ON COLUMN OPERAT_LOG.OPERAT_LOG_REQUEST_PARAMETER IS '请求参数';
COMMENT ON COLUMN OPERAT_LOG.OPERAT_LOG_RETURN_PARAMETERS IS '返回参数';
COMMENT ON COLUMN OPERAT_LOG.OPERAT_LOG_CONTENT IS '操作内容';
COMMENT ON COLUMN OPERAT_LOG.CREATED_TIME IS '创建时间 精确到秒';
COMMENT ON COLUMN OPERAT_LOG.UPDATED_TIME IS '修改时间 精确到秒';
COMMENT ON COLUMN OPERAT_LOG.REVISION IS '乐观锁';
COMMENT ON COLUMN OPERAT_LOG.IS_DELETED IS '逻辑删除 0:未删 1:已删';

/*创建自增序列*/
CREATE SEQUENCE OPERAT_LOG_ID
--最小值
MINVALUE 1
--不设置最大值
NOMAXVALUE
--从1开始计数
START WITH 1
--每次加1
INCREMENT BY 1
--一直累加，不循环
NOCYCLE
--不建缓冲区
NOCACHE;


--创建默认参保方案表
CREATE TABLE DEF_INSURED(
DEF_INSURED_ID NUMBER(10) PRIMARY KEY   NOT NULL,--默认参保方案编号
DEF_INSURED_NAME VARCHAR2(100) NOT NULL,--默认参保方案名称
DEF_INSURED_STATE NUMBER(10) DEFAULT 0  CHECK (DEF_INSURED_STATE IN (0,1)) NOT NULL,--默认参保方案状态 0:启用 1:禁用
DEF_INSURED_NUMBER NUMBER(10) DEFAULT 0  NOT NULL,--默认参保方案数量
CREATED_TIME DATE NOT NULL,-- 创建时间 精确到秒
UPDATED_TIME DATE NOT NULL,-- 修改时间 精确到秒
REVISION NUMBER(10) DEFAULT  1 NOT NULL,-- 乐观锁
IS_DELETED NUMBER(10) DEFAULT 0 CHECK(IS_DELETED IN(0,1))-- 逻辑删除 0:未删 1:已删
);

COMMENT ON TABLE DEF_INSURED IS '默认参保方案表';
COMMENT ON COLUMN DEF_INSURED.DEF_INSURED_ID IS '默认参保方案编号';
COMMENT ON COLUMN DEF_INSURED.DEF_INSURED_NAME IS '默认参保方案名称';
COMMENT ON COLUMN DEF_INSURED.DEF_INSURED_STATE IS '默认参保方案状态 0:启用 1:禁用';
COMMENT ON COLUMN DEF_INSURED.DEF_INSURED_NUMBER IS '默认参保方案数量';
COMMENT ON COLUMN DEF_INSURED.CREATED_TIME IS '创建时间 精确到秒';
COMMENT ON COLUMN DEF_INSURED.UPDATED_TIME IS '修改时间 精确到秒';
COMMENT ON COLUMN DEF_INSURED.REVISION IS '乐观锁';
COMMENT ON COLUMN DEF_INSURED.IS_DELETED IS '逻辑删除 0:未删 1:已删';

/*创建自增序列*/
CREATE SEQUENCE DEF_INSURED_ID
--最小值
MINVALUE 1
--不设置最大值
NOMAXVALUE
--从1开始计数
START WITH 1
--每次加1
INCREMENT BY 1
--一直累加，不循环
NOCYCLE
--不建缓冲区
NOCACHE;



--创建默认方案表
CREATE TABLE  DEF_SCHEME(
DEF_SCHEME_ID NUMBER(10) PRIMARY KEY   NOT NULL,--默认方案表编号
DEF_INSURED_ID NUMBER(10) NOT NULL,-- 默认参保方案编号
DEF_SCHEME_MIN NUMBER(10,2) DEFAULT 0 NOT NULL,-- 最少基数 
DEF_SCHEME_MAX NUMBER(10,2) DEFAULT 0 NOT NULL,-- 最多基数 
DEF_SCHEME_UPPER NUMBER(10,2) DEFAULT 0 NOT NULL,-- 基数上限
DEF_SCHEME_FLOOR NUMBER(10,2) DEFAULT 0 NOT NULL,-- 基数下限
DEF_SCHEME_PERSON_PROP NUMBER(10,2) DEFAULT 0 NOT NULL,-- 个人缴纳比例
DEF_SCHEME_PERSON_SUM NUMBER(10,2) DEFAULT 0 NOT NULL,-- 个人固定缴纳
DEF_SCHEME_FIRM_PROP NUMBER(10,2) DEFAULT 0 NOT NULL,-- 企业缴纳比例
DEF_SCHEME_FIRM_SUM NUMBER(10,2) DEFAULT 0 NOT NULL,-- 企业固定缴纳
DEF_SCHEME_TYPE VARCHAR2(20) NOT NULL,--参保类型
CREATED_TIME DATE NOT NULL,-- 创建时间 精确到秒
UPDATED_TIME DATE NOT NULL,-- 修改时间 精确到秒
REVISION NUMBER(10) DEFAULT  1 NOT NULL,-- 乐观锁
IS_DELETED NUMBER(10) DEFAULT 0 CHECK(IS_DELETED IN(0,1))-- 逻辑删除 0:未删 1:已删
);


COMMENT ON TABLE DEF_SCHEME IS '默认方案表';
COMMENT ON COLUMN DEF_SCHEME.DEF_SCHEME_ID IS '默认方案表编号';
COMMENT ON COLUMN DEF_SCHEME.DEF_INSURED_ID IS '默认参保方案编号';
COMMENT ON COLUMN DEF_SCHEME.DEF_SCHEME_MIN IS '最少基数';
COMMENT ON COLUMN DEF_SCHEME.DEF_SCHEME_MAX IS '最多基数';
COMMENT ON COLUMN DEF_SCHEME.DEF_SCHEME_UPPER IS '基数上限';
COMMENT ON COLUMN DEF_SCHEME.DEF_SCHEME_FLOOR IS '基数下限';
COMMENT ON COLUMN DEF_SCHEME.DEF_SCHEME_PERSON_PROP IS '个人缴纳比例';
COMMENT ON COLUMN DEF_SCHEME.DEF_SCHEME_PERSON_SUM IS '个人固定缴纳';
COMMENT ON COLUMN DEF_SCHEME.DEF_SCHEME_FIRM_PROP IS '企业缴纳比例';
COMMENT ON COLUMN DEF_SCHEME.DEF_SCHEME_FIRM_SUM IS '企业缴纳比例';
COMMENT ON COLUMN DEF_SCHEME.DEF_SCHEME_TYPE IS '参保类型';
COMMENT ON COLUMN DEF_SCHEME.CREATED_TIME IS '创建时间 精确到秒';
COMMENT ON COLUMN DEF_SCHEME.UPDATED_TIME IS '修改时间 精确到秒';
COMMENT ON COLUMN DEF_SCHEME.REVISION IS '乐观锁';
COMMENT ON COLUMN DEF_SCHEME.IS_DELETED IS '逻辑删除 0:未删 1:已删';

/*创建自增序列*/
CREATE SEQUENCE DEF_SCHEME_ID
--最小值
MINVALUE 1
--不设置最大值
NOMAXVALUE
--从1开始计数
START WITH 1
--每次加1
INCREMENT BY 1
--一直累加，不循环
NOCYCLE
--不建缓冲区
NOCACHE;


--创建参保方案表
CREATE TABLE INSURED_SCHEME(
INSURED_SCHEME_ID NUMBER(10) PRIMARY KEY   NOT NULL,--参保方案编号
STAFF_ID NUMBER(10) NOT NULL,--员工编号
DEF_INSURED_ID NUMBER(10) NOT NULL,--默认参保方案编号
CREATED_TIME DATE NOT NULL,-- 创建时间 精确到秒
UPDATED_TIME DATE NOT NULL,-- 修改时间 精确到秒
REVISION NUMBER(10) DEFAULT  1 NOT NULL-- 乐观锁
);

COMMENT ON TABLE INSURED_SCHEME IS '参保方案表';
COMMENT ON COLUMN INSURED_SCHEME.INSURED_SCHEME_ID IS '参保方案编号';
COMMENT ON COLUMN INSURED_SCHEME.STAFF_ID IS '员工编号';
COMMENT ON COLUMN INSURED_SCHEME.DEF_INSURED_ID IS '默认参保方案编号';
COMMENT ON COLUMN INSURED_SCHEME.CREATED_TIME IS '创建时间 精确到秒';
COMMENT ON COLUMN INSURED_SCHEME.UPDATED_TIME IS '修改时间 精确到秒';
COMMENT ON COLUMN INSURED_SCHEME.REVISION IS '乐观锁';


/*创建自增序列*/
CREATE SEQUENCE INSURED_SCHEME_ID
--最小值
MINVALUE 1
--不设置最大值
NOMAXVALUE
--从1开始计数
START WITH 1
--每次加1
INCREMENT BY 1
--一直累加，不循环
NOCYCLE
--不建缓冲区
NOCACHE;

--创建参保缴纳表
CREATE TABLE INSURED_PAYMENT(
INSURED_PAYMENT_ID NUMBER(10) PRIMARY KEY   NOT NULL,--参保缴纳编号
STAFF_ID NUMBER(10) NOT NULL,--员工编号
INSURED_SCHEME_ID NUMBER(10) NOT NULL,--参保方案编号 
INS_DETAIL_ID NUMBER(10) NOT NULL,--参保明细编号
INSURED_PAYMENT_SOCIAL_NUMBER NUMBER(10,2) DEFAULT 0 NOT NULL,--社保缴纳基数
INSURED_PAYMENT_FUND_NUMBER NUMBER(10,2) DEFAULT 0 NOT NULL,--积金缴纳基数
INSURED_PAYMENT_INSURED_MONTH DATE NOT NULL ,--参保月份 精确到年月
INSURED_PAYMENT_SALARY_MONTH DATE NOT NULL,--计薪月份 精确到年月
CREATED_TIME DATE NOT NULL,-- 创建时间 精确到秒
UPDATED_TIME DATE NOT NULL,-- 修改时间 精确到秒
REVISION NUMBER(10) DEFAULT  1 NOT NULL-- 乐观锁
);


COMMENT ON TABLE INSURED_PAYMENT IS '参保方案表';
COMMENT ON COLUMN INSURED_PAYMENT.INSURED_PAYMENT_ID IS '参保缴纳编号';
COMMENT ON COLUMN INSURED_PAYMENT.STAFF_ID IS '员工编号';
COMMENT ON COLUMN INSURED_PAYMENT.INSURED_SCHEME_ID IS '参保方案编号';
COMMENT ON COLUMN INSURED_PAYMENT.INS_DETAIL_ID IS '参保明细编号';
COMMENT ON COLUMN INSURED_PAYMENT.INSURED_PAYMENT_SOCIAL_NUMBER IS '社保缴纳基数';
COMMENT ON COLUMN INSURED_PAYMENT.INSURED_PAYMENT_FUND_NUMBER IS '积金缴纳基数';
COMMENT ON COLUMN INSURED_PAYMENT.INSURED_PAYMENT_INSURED_MONTH IS '参保月份 精确到年月';
COMMENT ON COLUMN INSURED_PAYMENT.INSURED_PAYMENT_SALARY_MONTH IS '计薪月份 精确到年月';
COMMENT ON COLUMN INSURED_PAYMENT.CREATED_TIME IS '创建时间 精确到秒';
COMMENT ON COLUMN INSURED_PAYMENT.UPDATED_TIME IS '修改时间 精确到秒';
COMMENT ON COLUMN INSURED_PAYMENT.REVISION IS '乐观锁';


/*创建自增序列*/
CREATE SEQUENCE INSURED_PAYMENT_ID
--最小值
MINVALUE 1
--不设置最大值
NOMAXVALUE
--从1开始计数
START WITH 1
--每次加1
INCREMENT BY 1
--一直累加，不循环
NOCYCLE
--不建缓冲区
NOCACHE;


--创建参保明细表
CREATE TABLE INSURED_DETAIL(
INS_DETAIL_ID NUMBER(10) PRIMARY KEY   NOT NULL,--参保明细编号
INS_DETAIL_STAFF_NAME VARCHAR2(20) NOT NULL,--员工名称
INS_DETAIL_INSURED_NAME VARCHAR2(100) NOT NULL,--参保方案名称
INS_DETAIL_INSURED_MONTH DATE NOT NULL,--参保月份 精确到年月
INS_DETAIL_SALARY_MONTH DATE NOT NULL,--计薪月份 精确到年月
INS_DETAIL_SOCIAL_PERSON_PAY NUMBER(10,2) DEFAULT 0 NOT NULL, --社保个人缴费
INS_DETAIL_SOCIAL_FIRM_PAY NUMBER(10,2) DEFAULT 0 NOT NULL, --社保公司缴费
INS_DETAIL_FUND_PERSON_PAY NUMBER(10,2) DEFAULT 0 NOT NULL, --积金个人缴费
INS_DETAIL_FUND_FIRM_PAY NUMBER(10,2) DEFAULT 0 NOT NULL, --积金公司缴费
CREATED_TIME DATE NOT NULL,-- 创建时间 精确到秒
UPDATED_TIME DATE NOT NULL,-- 修改时间 精确到秒
REVISION NUMBER(10) DEFAULT  1 NOT NULL-- 乐观锁
);


COMMENT ON TABLE INSURED_DETAIL IS '参保明细表';
COMMENT ON COLUMN INSURED_DETAIL.INS_DETAIL_ID IS '参保明细编号';
COMMENT ON COLUMN INSURED_DETAIL.INS_DETAIL_STAFF_NAME IS '员工名称';
COMMENT ON COLUMN INSURED_DETAIL.INS_DETAIL_INSURED_NAME IS '参保方案名称';
COMMENT ON COLUMN INSURED_DETAIL.INS_DETAIL_INSURED_MONTH IS '参保月份 精确到年月';
COMMENT ON COLUMN INSURED_DETAIL.INS_DETAIL_SALARY_MONTH IS '计薪月份 精确到年月';
COMMENT ON COLUMN INSURED_DETAIL.INS_DETAIL_SOCIAL_PERSON_PAY IS '社保个人缴费';
COMMENT ON COLUMN INSURED_DETAIL.INS_DETAIL_SOCIAL_FIRM_PAY IS '社保公司缴费';
COMMENT ON COLUMN INSURED_DETAIL.INS_DETAIL_FUND_PERSON_PAY IS '积金个人缴费';
COMMENT ON COLUMN INSURED_DETAIL.INS_DETAIL_FUND_FIRM_PAY IS '积金公司缴费';
COMMENT ON COLUMN INSURED_DETAIL.CREATED_TIME IS '创建时间 精确到秒';
COMMENT ON COLUMN INSURED_DETAIL.UPDATED_TIME IS '修改时间 精确到秒';
COMMENT ON COLUMN INSURED_DETAIL.REVISION IS '乐观锁';



/*创建自增序列*/
CREATE SEQUENCE INS_DETAIL_ID
--最小值
MINVALUE 1
--不设置最大值
NOMAXVALUE
--从1开始计数
START WITH 1
--每次加1
INCREMENT BY 1
--一直累加，不循环
NOCYCLE
--不建缓冲区
NOCACHE;


--创建参保归档表 
CREATE TABLE INSURED_ARCHIVE(
INS_ARCHIVE_ID NUMBER(10) PRIMARY KEY   NOT NULL,--参保归档编号
INS_ARCHIVE_SOCIAL_NUMBER NUMBER(10,2) DEFAULT 0 NOT NULL,-- 社保基数 
INS_ARCHIVE_FUND_NUMBER NUMBER(10,2) DEFAULT 0 NOT NULL,-- 积金基数
INS_ARCHIVE_SOCIAL_MAX NUMBER(10,2) DEFAULT 0 NOT NULL,-- 最多基数 
INS_ARCHIVE_SOCIAL_MIN NUMBER(10,2) DEFAULT 0 NOT NULL,-- 最少基数 
INS_ARCHIVE_FUND_MIN NUMBER(10,2) DEFAULT 0 NOT NULL,-- 最少基数 
INS_ARCHIVE_FUND_MAX NUMBER(10,2) DEFAULT 0 NOT NULL,-- 最多基数
INS_ARCHIVE_PR_NUMBER NUMBER(10,2) DEFAULT 0 NOT NULL,-- 养老保险基数
INS_ARCHIVE_PR_UPPER NUMBER(10,2) DEFAULT 0 NOT NULL,-- 基数上限
INS_ARCHIVE_PR_FLOOR NUMBER(10,2) DEFAULT 0 NOT NULL,-- 基数下限
INS_ARCHIVE_PR_PERSON_PROP NUMBER(10,2) DEFAULT 0 NOT NULL,-- 养老保险个人缴纳比例
INS_ARCHIVE_PR_PERSON_SUM NUMBER(10,2) DEFAULT 0 NOT NULL,-- 养老保险个人固定缴纳
INS_ARCHIVE_PR_FIRM_PROP NUMBER(10,2) DEFAULT 0 NOT NULL,-- 养老保险企业缴纳比例
INS_ARCHIVE_PR_FIRM_SUM NUMBER(10,2) DEFAULT 0 NOT NULL,-- 养老保险企业固定缴纳
INS_ARCHIVE_MD_NUMBER NUMBER(10,2) DEFAULT 0 NOT NULL,-- 医疗保险基数 
INS_ARCHIVE_MD_UPPER NUMBER(10,2) DEFAULT 0 NOT NULL,-- 基数上限
INS_ARCHIVE_MD_FLOOR NUMBER(10,2) DEFAULT 0 NOT NULL,-- 基数下限
INS_ARCHIVE_MD_PERSON_PROP NUMBER(10,2) DEFAULT 0 NOT NULL,-- 医疗保险个人缴纳比例
INS_ARCHIVE_MD_PERSON_SUM NUMBER(10,2) DEFAULT 0 NOT NULL,-- 医疗保险个人固定缴纳
INS_ARCHIVE_MD_FIRM_PROP NUMBER(10,2) DEFAULT 0 NOT NULL,-- 医疗保险企业缴纳比例
INS_ARCHIVE_MD_FIRM_SUM NUMBER(10,2) DEFAULT 0 NOT NULL,-- 医疗保险企业固定缴纳
INS_ARCHIVE_UN_NUMBER NUMBER(10,2) DEFAULT 0 NOT NULL,-- 失业保险基数 
INS_ARCHIVE_UN_UPPER NUMBER(10,2) DEFAULT 0 NOT NULL,-- 基数上限
INS_ARCHIVE_UN_FLOOR NUMBER(10,2) DEFAULT 0 NOT NULL,-- 基数下限
INS_ARCHIVE_UN_PERSON_PROP NUMBER(10,2) DEFAULT 0 NOT NULL,-- 失业保险个人缴纳比例
INS_ARCHIVE_UN_PERSON_SUM NUMBER(10,2) DEFAULT 0 NOT NULL,-- 失业保险个人固定缴纳
INS_ARCHIVE_UN_FIRM_PROP NUMBER(10,2) DEFAULT 0 NOT NULL,-- 失业保险企业缴纳比例
INS_ARCHIVE_UN_FIRM_SUM NUMBER(10,2) DEFAULT 0 NOT NULL,-- 失业保险企业固定缴纳
INS_ARCHIVE_OC_NUMBER NUMBER(10,2) DEFAULT 0 NOT NULL,-- 工伤保险基数 
INS_ARCHIVE_OC_UPPER NUMBER(10,2) DEFAULT 0 NOT NULL,-- 基数上限
INS_ARCHIVE_OC_FLOOR NUMBER(10,2) DEFAULT 0 NOT NULL,-- 基数下限
INS_ARCHIVE_OC_PERSON_PROP NUMBER(10,2) DEFAULT 0 NOT NULL,-- 工伤保险个人缴纳比例
INS_ARCHIVE_OC_PERSON_SUM NUMBER(10,2) DEFAULT 0 NOT NULL,-- 工伤保险个人固定缴纳
INS_ARCHIVE_OC_FIRM_PROP NUMBER(10,2) DEFAULT 0 NOT NULL,-- 工伤保险企业缴纳比例
INS_ARCHIVE_OC_FIRM_SUM NUMBER(10,2) DEFAULT 0 NOT NULL,-- 工伤保险企业固定缴纳
INS_ARCHIVE_GI_NUMBER NUMBER(10,2) DEFAULT 0 NOT NULL,-- 生育保险基数 
INS_ARCHIVE_GI_UPPER NUMBER(10,2) DEFAULT 0 NOT NULL,-- 基数上限
INS_ARCHIVE_GI_FLOOR NUMBER(10,2) DEFAULT 0 NOT NULL,-- 基数下限
INS_ARCHIVE_GI_PERSON_PROP NUMBER(10,2) DEFAULT 0 NOT NULL,-- 生育保险个人缴纳比例
INS_ARCHIVE_GI_PERSON_SUM NUMBER(10,2) DEFAULT 0 NOT NULL,-- 生育保险个人固定缴纳
INS_ARCHIVE_GI_FIRM_PROP NUMBER(10,2) DEFAULT 0 NOT NULL,-- 生育保险企业缴纳比例
INS_ARCHIVE_GI_FIRM_SUM NUMBER(10,2) DEFAULT 0 NOT NULL,-- 生育保险企业固定缴纳
INS_ARCHIVE_FU_NUMBER NUMBER(10,2) DEFAULT 0 NOT NULL,-- 积金基数 
INS_ARCHIVE_FU_UPPER NUMBER(10,2) DEFAULT 0 NOT NULL,-- 基数上限
INS_ARCHIVE_FU_FLOOR NUMBER(10,2) DEFAULT 0 NOT NULL,-- 基数下限
INS_ARCHIVE_FU_PERSON_PROP NUMBER(10,2) DEFAULT 0 NOT NULL,-- 积金个人缴纳比例
INS_ARCHIVE_FU_PERSON_SUM NUMBER(10,2) DEFAULT 0 NOT NULL,-- 积金个人固定缴纳
INS_ARCHIVE_FU_FIRM_PROP NUMBER(10,2) DEFAULT 0 NOT NULL,-- 积金企业缴纳比例
INS_ARCHIVE_FU_FIRM_SUM NUMBER(10,2) DEFAULT 0 NOT NULL,-- 积金企业固定缴纳
INS_ARCHIVE_NAME VARCHAR2(30) NOT NULL,--归档名称
INS_ARCHIVE_STAFF_NAME VARCHAR2(20) NOT NULL,--员工名称
INS_ARCHIVE_DEPT_NAME VARCHAR2(20) NOT NULL,--部门名称
INS_ARCHIVE_POST_NAME VARCHAR2(20) NOT NULL,--职位名称
INS_ARCHIVE_INSURED_NAME VARCHAR2(100) NOT NULL,--参保方案名称           
INS_ARCHIVE_INSURED_MONTH DATE NOT NULL,--参保月份 精确到年月
INS_ARCHIVE_SALARY_MONTH DATE NOT NULL,--计薪月份 精确到年月
INS_ARCHIVE_SOCIAL_PERSON_PAY NUMBER(10,2) DEFAULT 0 NOT NULL, --社保个人缴费
INS_ARCHIVE_SOCIAL_FIRM_PAY NUMBER(10,2) DEFAULT 0 NOT NULL, --社保公司缴费
INS_ARCHIVE_FUND_PERSON_PAY NUMBER(10,2) DEFAULT 0 NOT NULL, --积金个人缴费
INS_ARCHIVE_FUND_FIRM_PAY NUMBER(10,2) DEFAULT 0 NOT NULL, --积金公司缴费
CREATED_TIME DATE NOT NULL,-- 创建时间 精确到秒
UPDATED_TIME DATE NOT NULL,-- 修改时间 精确到秒
REVISION NUMBER(10) DEFAULT  1 NOT NULL,-- 乐观锁
IS_DELETED NUMBER(10) DEFAULT 0 CHECK(IS_DELETED IN(0,1))-- 逻辑删除 0:未删 1:已删
);


COMMENT ON TABLE INSURED_ARCHIVE IS '参保归档表';
COMMENT ON COLUMN INSURED_ARCHIVE.INS_ARCHIVE_ID IS '参保归档编号';
COMMENT ON COLUMN INSURED_ARCHIVE.INS_ARCHIVE_SOCIAL_NUMBER IS '社保基数 ';
COMMENT ON COLUMN INSURED_ARCHIVE.INS_ARCHIVE_FUND_NUMBER IS '积金基数 ';
COMMENT ON COLUMN INSURED_ARCHIVE.INS_ARCHIVE_PR_NUMBER IS ' 养老保险基数 ';
COMMENT ON COLUMN INSURED_ARCHIVE.INS_ARCHIVE_PR_UPPER IS '基数上限 ';
COMMENT ON COLUMN INSURED_ARCHIVE.INS_ARCHIVE_PR_FLOOR IS '基数下限 ';
COMMENT ON COLUMN INSURED_ARCHIVE.INS_ARCHIVE_PR_PERSON_PROP IS '养老保险个人缴纳比例';
COMMENT ON COLUMN INSURED_ARCHIVE.INS_ARCHIVE_PR_PERSON_SUM IS '养老保险个人固定缴纳';
COMMENT ON COLUMN INSURED_ARCHIVE.INS_ARCHIVE_PR_FIRM_PROP IS '养老保险企业缴纳比例';
COMMENT ON COLUMN INSURED_ARCHIVE.INS_ARCHIVE_PR_FIRM_SUM IS '养老保险企业固定缴纳';
COMMENT ON COLUMN INSURED_ARCHIVE.INS_ARCHIVE_MD_NUMBER IS '医疗保险基数 ';
COMMENT ON COLUMN INSURED_ARCHIVE.INS_ARCHIVE_MD_UPPER IS '基数上限 ';
COMMENT ON COLUMN INSURED_ARCHIVE.INS_ARCHIVE_MD_FLOOR IS '基数下限 ';
COMMENT ON COLUMN INSURED_ARCHIVE.INS_ARCHIVE_MD_PERSON_PROP IS '医疗保险个人缴纳比例';
COMMENT ON COLUMN INSURED_ARCHIVE.INS_ARCHIVE_MD_PERSON_SUM IS '医疗保险个人固定缴纳';
COMMENT ON COLUMN INSURED_ARCHIVE.INS_ARCHIVE_MD_FIRM_PROP  IS ' 医疗保险企业缴纳比例';
COMMENT ON COLUMN INSURED_ARCHIVE.INS_ARCHIVE_MD_FIRM_SUM  IS '医疗保险企业固定缴纳';
COMMENT ON COLUMN INSURED_ARCHIVE.INS_ARCHIVE_UN_NUMBER  IS '失业保险基数 ';
COMMENT ON COLUMN INSURED_ARCHIVE.INS_ARCHIVE_UN_UPPER IS '基数上限 ';
COMMENT ON COLUMN INSURED_ARCHIVE.INS_ARCHIVE_UN_FLOOR IS '基数下限 ';
COMMENT ON COLUMN INSURED_ARCHIVE.INS_ARCHIVE_UN_PERSON_PROP  IS '失业保险个人缴纳比例';
COMMENT ON COLUMN INSURED_ARCHIVE.INS_ARCHIVE_UN_PERSON_SUM  IS '失业保险个人固定缴纳';
COMMENT ON COLUMN INSURED_ARCHIVE.INS_ARCHIVE_UN_FIRM_PROP  IS '失业保险企业缴纳比例';
COMMENT ON COLUMN INSURED_ARCHIVE.INS_ARCHIVE_UN_FIRM_SUM  IS '失业保险企业固定缴纳';
COMMENT ON COLUMN INSURED_ARCHIVE.INS_ARCHIVE_OC_NUMBER  IS '工伤保险基数 ';
COMMENT ON COLUMN INSURED_ARCHIVE.INS_ARCHIVE_OC_UPPER IS '基数上限 ';
COMMENT ON COLUMN INSURED_ARCHIVE.INS_ARCHIVE_OC_FLOOR IS '基数下限 ';
COMMENT ON COLUMN INSURED_ARCHIVE.INS_ARCHIVE_OC_PERSON_PROP  IS '工伤保险个人缴纳比例';
COMMENT ON COLUMN INSURED_ARCHIVE.INS_ARCHIVE_OC_PERSON_SUM  IS '工伤保险个人固定缴纳';
COMMENT ON COLUMN INSURED_ARCHIVE.INS_ARCHIVE_OC_FIRM_PROP  IS '工伤保险企业缴纳比例';
COMMENT ON COLUMN INSURED_ARCHIVE.INS_ARCHIVE_OC_FIRM_SUM  IS '工伤保险企业固定缴纳';
COMMENT ON COLUMN INSURED_ARCHIVE.INS_ARCHIVE_GI_NUMBER  IS '生育保险基数 ';
COMMENT ON COLUMN INSURED_ARCHIVE.INS_ARCHIVE_GI_UPPER IS '基数上限 ';
COMMENT ON COLUMN INSURED_ARCHIVE.INS_ARCHIVE_GI_FLOOR IS '基数下限 ';
COMMENT ON COLUMN INSURED_ARCHIVE.INS_ARCHIVE_GI_PERSON_PROP  IS ' 生育保险个人缴纳比例';
COMMENT ON COLUMN INSURED_ARCHIVE.INS_ARCHIVE_GI_PERSON_SUM  IS '生育保险个人固定缴纳';
COMMENT ON COLUMN INSURED_ARCHIVE.INS_ARCHIVE_GI_FIRM_PROP  IS ' 生育保险企业缴纳比例';
COMMENT ON COLUMN INSURED_ARCHIVE.INS_ARCHIVE_GI_FIRM_SUM  IS '生育保险企业固定缴纳';
COMMENT ON COLUMN INSURED_ARCHIVE.INS_ARCHIVE_FU_NUMBER  IS '积金基数 ';
COMMENT ON COLUMN INSURED_ARCHIVE.INS_ARCHIVE_FU_UPPER IS '基数上限 ';
COMMENT ON COLUMN INSURED_ARCHIVE.INS_ARCHIVE_FU_FLOOR IS '基数下限 ';
COMMENT ON COLUMN INSURED_ARCHIVE.INS_ARCHIVE_FU_PERSON_PROP  IS '积金个人缴纳比例';
COMMENT ON COLUMN INSURED_ARCHIVE.INS_ARCHIVE_FU_PERSON_SUM  IS '积金个人固定缴纳';
COMMENT ON COLUMN INSURED_ARCHIVE.INS_ARCHIVE_FU_FIRM_PROP  IS '积金企业缴纳比例';
COMMENT ON COLUMN INSURED_ARCHIVE.INS_ARCHIVE_FU_FIRM_SUM  IS '积金企业固定缴纳';
COMMENT ON COLUMN INSURED_ARCHIVE.INS_ARCHIVE_NAME  IS '归档名称';
COMMENT ON COLUMN INSURED_ARCHIVE.INS_ARCHIVE_STAFF_NAME  IS '员工名称';
COMMENT ON COLUMN INSURED_ARCHIVE.INS_ARCHIVE_DEPT_NAME  IS '部门名称';
COMMENT ON COLUMN INSURED_ARCHIVE.INS_ARCHIVE_POST_NAME  IS '职位名称';
COMMENT ON COLUMN INSURED_ARCHIVE.INS_ARCHIVE_INSURED_NAME  IS '参保方案名称';
COMMENT ON COLUMN INSURED_ARCHIVE.INS_ARCHIVE_INSURED_MONTH  IS '参保月份 精确到年月';
COMMENT ON COLUMN INSURED_ARCHIVE.INS_ARCHIVE_SALARY_MONTH  IS '计薪月份 精确到年月';
COMMENT ON COLUMN INSURED_ARCHIVE.INS_ARCHIVE_SOCIAL_PERSON_PAY  IS '社保个人缴费';
COMMENT ON COLUMN INSURED_ARCHIVE.INS_ARCHIVE_SOCIAL_FIRM_PAY  IS '社保公司缴费';
COMMENT ON COLUMN INSURED_ARCHIVE.INS_ARCHIVE_FUND_PERSON_PAY  IS '积金个人缴费';
COMMENT ON COLUMN INSURED_ARCHIVE.INS_ARCHIVE_FUND_FIRM_PAY  IS '积金公司缴费';
COMMENT ON COLUMN INSURED_ARCHIVE.CREATED_TIME  IS '创建时间 精确到秒';
COMMENT ON COLUMN INSURED_ARCHIVE.UPDATED_TIME  IS '修改时间 精确到秒';
COMMENT ON COLUMN INSURED_ARCHIVE.REVISION  IS '乐观锁';
COMMENT ON COLUMN INSURED_ARCHIVE.IS_DELETED IS '逻辑删除 0:未删 1:已删 ';

/*创建自增序列*/
CREATE SEQUENCE INSURED_ARCHIVE_ID
--最小值
MINVALUE 1
--不设置最大值
NOMAXVALUE
--从1开始计数
START WITH 1
--每次加1
INCREMENT BY 1
--一直累加，不循环
NOCYCLE
--不建缓冲区
NOCACHE;


--创建参保日志表
CREATE TABLE INSURED_LOG(
INS_LOG_ID NUMBER(10) PRIMARY KEY   NOT NULL,--参保日志编号
INS_LOG_ID_THE_INSURED VARCHAR2(20) NOT NULL,--参保人
INS_LOG_UPDATE_OBJECT VARCHAR2(20) NOT NULL,--修改对象
INS_LOG_EXPLAIN VARCHAR2(100) NOT NULL,--日志说明
INS_LOG_INSURED_NAME VARCHAR2(100) NOT NULL,--参保方案
INS_LOG_SOCIAL_NUMBER NUMBER(10) DEFAULT 0 NOT NULL,-- 社保基数 
INS_LOG_SOCIAL_INSURED_MONTH DATE,-- 社保参保月份 精确到年月
INS_LOG_SOCIAL_SALARY_MONTH DATE,-- 社保计薪月份  精确到年月
INS_LOG_FUND_NUMBER NUMBER(10) DEFAULT 0 NOT NULL,-- 积金基数 
INS_LOG_FUND_INSURED_MONTH DATE,-- 积金参保月份 精确到年月
INS_LOG_FUND_SALARY_MONTH DATE,-- 积金计薪月份 精确到年月
INS_LOG_COLOR varchar2(30) not null,--颜色
CREATED_TIME DATE NOT NULL,-- 创建时间 精确到秒
UPDATED_TIME DATE NOT NULL,-- 修改时间 精确到秒
REVISION NUMBER(10) DEFAULT  1 NOT NULL,-- 乐观锁
IS_DELETED NUMBER(10) DEFAULT 0 CHECK(IS_DELETED IN(0,1))-- 逻辑删除 0:未删 1:已删  
);



COMMENT ON TABLE INSURED_LOG IS '参保日志表';
COMMENT ON COLUMN INSURED_LOG.INS_LOG_ID IS '参保日志编号';
COMMENT ON COLUMN INSURED_LOG.INS_LOG_ID_THE_INSURED IS '参保人';
COMMENT ON COLUMN INSURED_LOG.INS_LOG_UPDATE_OBJECT IS '修改对象';
COMMENT ON COLUMN INSURED_LOG.INS_LOG_EXPLAIN IS '日志说明';
COMMENT ON COLUMN INSURED_LOG.INS_LOG_INSURED_NAME IS '参保方案';
COMMENT ON COLUMN INSURED_LOG.INS_LOG_SOCIAL_NUMBER IS '社保基数';
COMMENT ON COLUMN INSURED_LOG.INS_LOG_SOCIAL_INSURED_MONTH IS '社保参保月份 精确到年月';
COMMENT ON COLUMN INSURED_LOG.INS_LOG_SOCIAL_SALARY_MONTH IS '社保计薪月份  精确到年月';
COMMENT ON COLUMN INSURED_LOG.INS_LOG_FUND_NUMBER IS '积金基数';
COMMENT ON COLUMN INSURED_LOG.INS_LOG_FUND_INSURED_MONTH IS '积金参保月份 精确到年月';
COMMENT ON COLUMN INSURED_LOG.INS_LOG_FUND_SALARY_MONTH IS '积金计薪月份 精确到年月';
COMMENT ON COLUMN INSURED_LOG.INS_LOG_COLOR IS '颜色';
COMMENT ON COLUMN INSURED_LOG.CREATED_TIME IS '创建时间 精确到秒';
COMMENT ON COLUMN INSURED_LOG.UPDATED_TIME IS '修改时间 精确到秒';
COMMENT ON COLUMN INSURED_LOG.REVISION IS '乐观锁';
COMMENT ON COLUMN INSURED_LOG.IS_DELETED IS '逻辑删除 0:未删 1:已删 ';

/*创建自增序列*/
CREATE SEQUENCE INSURED_LOG_ID
--最小值
MINVALUE 1
--不设置最大值
NOMAXVALUE
--从1开始计数
START WITH 1
--每次加1
INCREMENT BY 1
--一直累加，不循环
NOCYCLE
--不建缓冲区
NOCACHE;













-- 创建月薪范围表

CREATE TABLE MONTHLY_SALARY(
MONTHLY_SALARY_ID NUMBER(10) PRIMARY KEY NOT NULL,    --编号
MONTHLY_SALARY_STAR NUMBER(10,2) DEFAULT 0 NOT NULL,              -- 月薪起始金额
MONTHLY_SALARY_END NUMBER(10,2) DEFAULT 0 NOT NULL,               -- 月薪结束金额
CREATED_TIME DATE NOT NULL,                   -- 创建时间
UPDATED_TIME DATE NOT NULL,                   -- 最后修改时间
REVISION NUMBER(10) DEFAULT  1 NOT NULL,                 -- 乐观锁
IS_DELETED NUMBER(10) DEFAULT 0 CHECK (IS_DELETED IN (0,1)) NOT NULL                   -- 逻辑删除
);



COMMENT ON TABLE MONTHLY_SALARY IS '月薪范围表';
COMMENT ON COLUMN MONTHLY_SALARY.MONTHLY_SALARY_ID IS '编号';
COMMENT ON COLUMN MONTHLY_SALARY.MONTHLY_SALARY_STAR IS '月薪起始金额';
COMMENT ON COLUMN MONTHLY_SALARY.MONTHLY_SALARY_END IS '月薪结束金额';
COMMENT ON COLUMN MONTHLY_SALARY.CREATED_TIME IS '创建时间';
COMMENT ON COLUMN MONTHLY_SALARY.UPDATED_TIME IS '最后修改时间';
COMMENT ON COLUMN MONTHLY_SALARY.REVISION IS '乐观锁';
COMMENT ON COLUMN MONTHLY_SALARY.IS_DELETED IS '逻辑删除;1表示删除，0 表示未删除';

/*创建自增序列*/
CREATE SEQUENCE MONTHLY_SALARY_ID
  --最小值
MINVALUE 1     
 --不设置最大值
NOMAXVALUE      
  --从1开始计数
START WITH 1   
 --每次加1
INCREMENT BY 1 
 --一直累加，不循环
NOCYCLE 
--不建缓冲区
NOCACHE;


-- 创建面试表
CREATE TABLE INTERVIEW(
INTERVIEW_ID NUMBER(10) PRIMARY KEY NOT NULL,   --编号
RESUME_ID NUMBER(10) NOT NULL,      -- 简历编号
INTERVIEW_BNAME VARCHAR2(10),           --被面试人
INTERVIEW_TIME DATE,		        -- 面试日期
INTERVIEW_STATE NUMBER(10) DEFAULT 0 CHECK (INTERVIEW_STATE IN (0,1,2,3,4,5)) NOT NULL,	-- 0:待面试  1:通过 2：复试 3：淘汰
INTERVIEW_EVALUATE VARCHAR2(200),    --面试评价
INTERVIEW_NAME VARCHAR2(10),           --面试官姓名
CREATED_TIME DATE NOT NULL,                   -- 创建时间
UPDATED_TIME DATE NOT NULL,                   -- 修改时间
REVISION NUMBER(10) DEFAULT  1 NOT NULL,                 -- 乐观锁
IS_DELETED NUMBER(10) DEFAULT 0 CHECK (IS_DELETED IN (0,1)) NOT NULL                   -- 逻辑删除
);

COMMENT ON TABLE INTERVIEW IS '面试表';
COMMENT ON COLUMN INTERVIEW.INTERVIEW_ID IS '编号';
COMMENT ON COLUMN INTERVIEW.RESUME_ID IS '简历编号';
COMMENT ON COLUMN INTERVIEW.INTERVIEW_BNAME IS '被面试人';
COMMENT ON COLUMN INTERVIEW.INTERVIEW_TIME IS '面试日期';
COMMENT ON COLUMN INTERVIEW.INTERVIEW_STATE IS '状态 0:待面试  1:通过 2：复试 3：淘汰';
COMMENT ON COLUMN INTERVIEW.INTERVIEW_EVALUATE IS '面试评价';
COMMENT ON COLUMN INTERVIEW.INTERVIEW_NAME IS '面试官';
COMMENT ON COLUMN INTERVIEW.CREATED_TIME IS '创建时间';
COMMENT ON COLUMN INTERVIEW.UPDATED_TIME IS '最后修改时间';
COMMENT ON COLUMN INTERVIEW.REVISION IS '乐观锁';
COMMENT ON COLUMN INTERVIEW.IS_DELETED IS '逻辑删除;1表示删除，0 表示未删除';

/*创建自增序列*/
CREATE SEQUENCE INTERVIEW_ID
  --最小值
MINVALUE 1     
 --不设置最大值
NOMAXVALUE      
  --从1开始计数
START WITH 1   
 --每次加1
INCREMENT BY 1 
-- 一直累加，不循环
NOCYCLE 
--不建缓冲区
NOCACHE;


-- 创建复试表
CREATE TABLE RETEST(
RETEST_ID NUMBER(10) PRIMARY KEY NOT NULL,   --复试编号
RESUME_ID NUMBER(10) NOT NULL,      -- 简历编号
RETEST_BNAME VARCHAR2(10) NOT NULL,           --被复试人
RETEST_TIME DATE NOT NULL,		    -- 复试日期
RETEST_STATE NUMBER(10) DEFAULT 0 CHECK (RETEST_STATE IN (0,1,2)) NOT NULL,		-- 状态 0:待复试 1:通过 2：淘汰
RETEST_EVALUATE VARCHAR2(200),    --复试评价
RETEST_NAME VARCHAR2(10) NOT NULL,           --复试官姓名
CREATED_TIME DATE NOT NULL,                   -- 创建时间
UPDATED_TIME DATE NOT NULL,                   -- 修改时间
REVISION NUMBER(10) DEFAULT  1 NOT NULL,                 -- 乐观锁
IS_DELETED NUMBER(10) DEFAULT 0 CHECK (IS_DELETED IN (0,1)) NOT NULL                   -- 逻辑删除
);



COMMENT ON TABLE RETEST IS '复试表';
COMMENT ON COLUMN RETEST.RETEST_ID IS '复试编号';
COMMENT ON COLUMN RETEST.RESUME_ID IS '简历编号';
COMMENT ON COLUMN RETEST.RETEST_BNAME IS '被复试人';
COMMENT ON COLUMN RETEST.RETEST_TIME IS '复试日期';
COMMENT ON COLUMN RETEST.RETEST_STATE IS '状态 0:待复试 1:通过 2：淘汰';
COMMENT ON COLUMN RETEST.RETEST_EVALUATE IS '复试评价';
COMMENT ON COLUMN RETEST.RETEST_NAME IS '复试官';
COMMENT ON COLUMN RETEST.CREATED_TIME IS '创建时间';
COMMENT ON COLUMN RETEST.UPDATED_TIME IS '修改时间';
COMMENT ON COLUMN RETEST.REVISION IS '乐观锁';
COMMENT ON COLUMN RETEST.IS_DELETED IS '逻辑删除;1表示删除，0 表示未删除';


/*创建自增序列*/
CREATE SEQUENCE RETEST_ID
  --最小值
MINVALUE 1     
 --不设置最大值
NOMAXVALUE      
  --从1开始计数
START WITH 1   
 --每次加1
INCREMENT BY 1 
 --一直累加，不循环
NOCYCLE 
--不建缓冲区
NOCACHE;


-- 创建教育经历表:员工
CREATE TABLE EDUCATION(
EDUCATION_ID NUMBER(10) PRIMARY KEY NOT NULL,   --编号
EDUCATION_START_TIME DATE,    --开始时间
EDUCATION_END_TIME DATE,    --结束时间
staff_id NUMBER(10)not null ,--员工外键
EDUCATION_STUDENTNAME VARCHAR2(100),   --学校名称
EDUCATION_MAJOR VARCHAR2(50),		--所属专业
EDUCATION_FULL_TIME NUMBER(10)  DEFAULT 0 CHECK (EDUCATION_FULL_TIME IN (0,1)),		--是否全日制 0:是  1:否
CREATED_TIME DATE NOT NULL,                   -- 创建时间
UPDATED_TIME DATE NOT NULL,                   -- 修改时间
REVISION NUMBER(10) DEFAULT  1 NOT NULL,                 -- 乐观锁
IS_DELETED NUMBER(10) DEFAULT 0 CHECK (IS_DELETED IN (0,1)) NOT NULL -- 逻辑删除
);

COMMENT ON TABLE EDUCATION IS '受教育经历表';
COMMENT ON COLUMN EDUCATION.STAFF_ID IS '员工编号外键';
COMMENT ON COLUMN EDUCATION.EDUCATION_ID IS '编号';
COMMENT ON COLUMN EDUCATION.EDUCATION_START_TIME IS '开始时间';
COMMENT ON COLUMN EDUCATION.EDUCATION_END_TIME IS '结束时间';
COMMENT ON COLUMN EDUCATION.EDUCATION_STUDENTNAME IS '学校名称';
COMMENT ON COLUMN EDUCATION.EDUCATION_MAJOR IS '所属专业';
COMMENT ON COLUMN EDUCATION.EDUCATION_FULL_TIME IS '是否全日制';
COMMENT ON COLUMN RETEST.CREATED_TIME IS '创建时间';
COMMENT ON COLUMN RETEST.UPDATED_TIME IS '修改时间';
COMMENT ON COLUMN RETEST.REVISION IS '乐观锁';
COMMENT ON COLUMN RETEST.IS_DELETED IS '逻辑删除;1表示删除，0 表示未删除';


/*创建自增序列*/
CREATE SEQUENCE EDUCATION_ID
  --最小值
MINVALUE 1     
 --不设置最大值
NOMAXVALUE      
  --从1开始计数
START WITH 1   
 --每次加1
INCREMENT BY 1 
 --一直累加，不循环
NOCYCLE 
--不建缓冲区
NOCACHE;


-- 创建教育经历表：简历
CREATE TABLE EDUCATIONSS(
EDUCATIONSS_ID NUMBER(10) PRIMARY KEY NOT NULL,   --编号
EDUCATION_START_TIME DATE NOT NULL,    --开始时间
EDUCATION_END_TIME DATE NOT NULL,    --结束时间
RESUME_ID NUMBER(10)not null, --简历表外键
EDUCATION_STUDENTNAME VARCHAR2(100),   --学校名称
EDUCATION_MAJOR VARCHAR2(50),		--所属专业
EDUCATION_FULL_TIME NUMBER(10)  DEFAULT 0 CHECK (EDUCATION_FULL_TIME IN (0,1)),		--是否全日制 0:是  1:否
CREATED_TIME DATE NOT NULL,                   -- 创建时间
UPDATED_TIME DATE NOT NULL,                   -- 修改时间
REVISION NUMBER(10) DEFAULT  1 NOT NULL,                 -- 乐观锁
IS_DELETED NUMBER(10) DEFAULT 0 CHECK (IS_DELETED IN (0,1)) NOT NULL -- 逻辑删除
);

COMMENT ON TABLE EDUCATIONSS IS '受教育经历表';
COMMENT ON COLUMN EDUCATIONSS.RESUME_ID IS '简历编号外键';
COMMENT ON COLUMN EDUCATIONSS.EDUCATIONSS_ID IS '编号';
COMMENT ON COLUMN EDUCATIONSS.EDUCATION_START_TIME IS '开始时间';
COMMENT ON COLUMN EDUCATIONSS.EDUCATION_END_TIME IS '结束时间';
COMMENT ON COLUMN EDUCATIONSS.EDUCATION_STUDENTNAME IS '学校名称';
COMMENT ON COLUMN EDUCATIONSS.EDUCATION_MAJOR IS '所属专业';
COMMENT ON COLUMN EDUCATIONSS.EDUCATION_FULL_TIME IS '是否全日制';
COMMENT ON COLUMN EDUCATIONSS.CREATED_TIME IS '创建时间';
COMMENT ON COLUMN EDUCATIONSS.UPDATED_TIME IS '修改时间';
COMMENT ON COLUMN EDUCATIONSS.REVISION IS '乐观锁';
COMMENT ON COLUMN EDUCATIONSS.IS_DELETED IS '逻辑删除;1表示删除，0 表示未删除';


/*创建自增序列*/
CREATE SEQUENCE EDUCATIONSS_ID
  --最小值
MINVALUE 1     
 --不设置最大值
NOMAXVALUE      
  --从1开始计数
START WITH 1   
 --每次加1
INCREMENT BY 1 
 --一直累加，不循环
NOCYCLE 
--不建缓冲区
NOCACHE;




-- 创建工作经历表：简历
CREATE TABLE WORK_EXPERIENCESS(
WORK_EXPERIENCESS_ID NUMBER(10) PRIMARY KEY NOT NULL,   --编号
WORK_STARE_TIME DATE NOT NULL,    --开始时间
WORK_END_TIME DATE NOT NULL,    --结束时间
RESUME_ID NUMBER(10)not null, --简历表外键
COMPANY_NAME VARCHAR2(200),     --公司名称
POSITION_NAME VARCHAR2(20),        --职位名称
POSITION_INDUSTRY VARCHAR2(20),     --所属行业
POSITION_DESCRIBE VARCHAR2(20),        --工作描述
POSITION_SQMONTHLY NUMBER(10),        --税前月薪
CREATED_TIME DATE NOT NULL,                   -- 创建时间
UPDATED_TIME DATE NOT NULL,                   -- 修改时间
REVISION NUMBER(10) DEFAULT  1 NOT NULL,                 -- 乐观锁
IS_DELETED NUMBER(10) DEFAULT 0 CHECK (IS_DELETED IN (0,1)) NOT NULL                   -- 逻辑删除
);

COMMENT ON TABLE WORK_EXPERIENCESS IS '工作经历表';
COMMENT ON COLUMN WORK_EXPERIENCESS.RESUME_ID IS '简历编号外键';
COMMENT ON COLUMN WORK_EXPERIENCESS.WORK_EXPERIENCESS_ID IS '编号';
COMMENT ON COLUMN WORK_EXPERIENCESS.WORK_STARE_TIME IS '开始时间';
COMMENT ON COLUMN WORK_EXPERIENCESS.WORK_END_TIME IS '结束时间';
COMMENT ON COLUMN WORK_EXPERIENCESS.COMPANY_NAME IS '公司名称';
COMMENT ON COLUMN WORK_EXPERIENCESS.POSITION_NAME IS '职位名称';
COMMENT ON COLUMN WORK_EXPERIENCESS.POSITION_INDUSTRY IS '所属行业';
COMMENT ON COLUMN WORK_EXPERIENCESS.POSITION_DESCRIBE IS '工作描述';
COMMENT ON COLUMN WORK_EXPERIENCESS.POSITION_SQMONTHLY IS '税前月薪';
COMMENT ON COLUMN WORK_EXPERIENCESS.CREATED_TIME IS '创建时间';
COMMENT ON COLUMN WORK_EXPERIENCESS.UPDATED_TIME IS '修改时间';
COMMENT ON COLUMN WORK_EXPERIENCESS.REVISION IS '乐观锁';
COMMENT ON COLUMN WORK_EXPERIENCESS.IS_DELETED IS '逻辑删除;1表示删除，0 表示未删除';

/*创建自增序列*/
CREATE SEQUENCE WORK_EXPERIENCESS_ID
  --最小值
MINVALUE 1     
 --不设置最大值
NOMAXVALUE      
  --从1开始计数
START WITH 1   
 --每次加1
INCREMENT BY 1 
 --一直累加，不循环
NOCYCLE 
--不建缓冲区
NOCACHE;











-- 工作经历表 ：员工
-- 创建工作经历表
CREATE TABLE WORK_EXPERIENCE(
WORK_EXPERIENCE_ID NUMBER(10) PRIMARY KEY NOT NULL,   --编号
WORK_STARE_TIME DATE,    --开始时间
WORK_END_TIME DATE,    --结束时间
STAFF_ID NUMBER(10)not null ,--员工外键
COMPANY_NAME VARCHAR2(200),     --公司名称
POSITION_NAME VARCHAR2(20),        --职位名称
POSITION_INDUSTRY VARCHAR2(20),     --所属行业
POSITION_DESCRIBE VARCHAR2(20),        --工作描述
POSITION_SQMONTHLY NUMBER(10),        --税前月薪
CREATED_TIME DATE NOT NULL,                   -- 创建时间
UPDATED_TIME DATE NOT NULL,                   -- 修改时间
REVISION NUMBER(10) DEFAULT  1 NOT NULL,                 -- 乐观锁
IS_DELETED NUMBER(10) DEFAULT 0 CHECK (IS_DELETED IN (0,1)) NOT NULL                   -- 逻辑删除
);

COMMENT ON TABLE WORK_EXPERIENCE IS '工作经历表';
COMMENT ON COLUMN WORK_EXPERIENCE.STAFF_ID IS '员工编号外键';
COMMENT ON COLUMN WORK_EXPERIENCE.WORK_EXPERIENCE_ID IS '编号';
COMMENT ON COLUMN WORK_EXPERIENCE.WORK_STARE_TIME IS '开始时间';
COMMENT ON COLUMN WORK_EXPERIENCE.WORK_END_TIME IS '结束时间';
COMMENT ON COLUMN WORK_EXPERIENCE.COMPANY_NAME IS '公司名称';
COMMENT ON COLUMN WORK_EXPERIENCE.POSITION_NAME IS '职位名称';
COMMENT ON COLUMN WORK_EXPERIENCE.POSITION_INDUSTRY IS '所属行业';
COMMENT ON COLUMN WORK_EXPERIENCE.POSITION_DESCRIBE IS '工作描述';
COMMENT ON COLUMN WORK_EXPERIENCE.POSITION_SQMONTHLY IS '税前月薪';
COMMENT ON COLUMN WORK_EXPERIENCE.CREATED_TIME IS '创建时间';
COMMENT ON COLUMN WORK_EXPERIENCE.UPDATED_TIME IS '修改时间';
COMMENT ON COLUMN WORK_EXPERIENCE.REVISION IS '乐观锁';
COMMENT ON COLUMN WORK_EXPERIENCE.IS_DELETED IS '逻辑删除;1表示删除，0 表示未删除';

/*创建自增序列*/
CREATE SEQUENCE WORK_EXPERIENCE_ID
  --最小值
MINVALUE 1     
 --不设置最大值
NOMAXVALUE      
  --从1开始计数
START WITH 1   
 --每次加1
INCREMENT BY 1 
 --一直累加，不循环
NOCYCLE 
--不建缓冲区
NOCACHE;



--创建简历表
CREATE TABLE RESUME(
RESUME_ID NUMBER(10) PRIMARY KEY NOT NULL,      -- 编号
RESUME_NAME VARCHAR2(20) NOT NULL,                     -- 名字
RESUME_SEX VARCHAR2(10) NOT NULL,                   -- 性别
RESUME_PHONE NUMBER(11) ,                   -- 手机号码
RESUME_EDUCATION VARCHAR2(10),               -- 学历名称
RESUME_MAILBOX VARCHAR2(50),                  -- 邮箱
RESUME_INTRODUCE VARCHAR2(2000),              -- 介绍
RESUME_BIRTHDAY DATE NOT NULL,                         -- 出生日期
RESUME_AGE NUMBER(3),                   -- 年龄
RESUME_RESIDENCE VARCHAR2(100) ,    -- 户口所在地
RECRUITMENT_PLAN_ID NUMBER(10),               -- 招聘计划编号
RESUME_POLITICAL_OUTLOOK VARCHAR2(10) ,               -- 政治面貌
RESUME_ZT NUMBER(5) DEFAULT 0 CHECK (RESUME_ZT IN (0,1,2,3,4,5)),                      -- 状态 
invite_state varchar2(20) ,   --  邀约状态  0：未邀约  1：已邀约 
TouJ_TIME DATE ,                     -- 投简时间
CREATED_TIME DATE NOT NULL,                     -- 创建时间
UPDATED_TIME DATE NOT NULL,                     -- 修改时间
REVISION NUMBER(10) DEFAULT  1 NOT NULL,                 -- 乐观锁
IS_DELETED NUMBER(10) DEFAULT 0 CHECK (IS_DELETED IN (0,1)) NOT NULL                   -- 逻辑删除
);




COMMENT ON TABLE RESUME IS '简历表';
COMMENT ON COLUMN RESUME.RESUME_ID IS '编号';
COMMENT ON COLUMN RESUME.RESUME_NAME IS '名字';
COMMENT ON COLUMN RESUME.RESUME_SEX IS '性别';
COMMENT ON COLUMN RESUME.RESUME_PHONE IS '手机号码';
COMMENT ON COLUMN RESUME.RESUME_EDUCATION IS '学历名称';
COMMENT ON COLUMN RESUME.RESUME_MAILBOX IS '邮箱';
COMMENT ON COLUMN RESUME.RESUME_INTRODUCE IS '介绍';
COMMENT ON COLUMN RESUME.RESUME_BIRTHDAY IS '出生日期';
COMMENT ON COLUMN RESUME.RESUME_AGE IS '年龄';
COMMENT ON COLUMN RESUME.RESUME_RESIDENCE IS '户口所在地';
COMMENT ON COLUMN RESUME.RESUME_ZT IS '0:新简历 1:候选人 2:淘汰库 3:面试候选人 4:已邀约';
COMMENT ON COLUMN RESUME.TouJ_TIME  IS '投简时间';
COMMENT ON COLUMN RESUME.CREATED_TIME IS '创建时间';
COMMENT ON COLUMN RESUME.UPDATED_TIME IS '修改时间';
COMMENT ON COLUMN RESUME.REVISION IS '乐观锁';
COMMENT ON COLUMN RESUME.IS_DELETED IS '逻辑删除;1表示删除，0 表示未删除';


/*创建自增序列*/
CREATE SEQUENCE RESUME_ID
  --最小值
MINVALUE 1     
 --不设置最大值
NOMAXVALUE      
  --从1开始计数
START WITH 1   
 --每次加1
INCREMENT BY 1 
 --一直累加，不循环
NOCYCLE 
--不建缓冲区
NOCACHE;




-- 创建录用表
CREATE TABLE EMPLOYMENT_TABLE(
EMPLOYMENT_ID NUMBER(10) PRIMARY KEY NOT NULL,         --编号
EMPLOYMENT_STATE NUMBER(30) DEFAULT 0 CHECK (EMPLOYMENT_STATE IN (0,1,2)) NOT NULL,	-- 状态 0:待入职 1:已入职 2：淘汰
RESUME_ID NUMBER(10) NOT NULL,             --简历编号
REMARKS VARCHAR2(99),		 -- 备注
EMPLOYMENT_HIREDATE date,			-- 录用时间
EMPLOYMENT_SALARY NUMBER NOT NULL,  --试用工资
EMPLOYMENT_SALARYZ NUMBER NOT NULL,  --正式工资
WAIVE_REASON VARCHAR2(50),                           --  放弃原因
CREATED_TIME DATE NOT NULL,                   -- 创建时间
UPDATED_TIME DATE NOT NULL,                   -- 修改时间
REVISION NUMBER(10) DEFAULT  1 NOT NULL,                 -- 乐观锁
IS_DELETED NUMBER(10) DEFAULT 0 CHECK (IS_DELETED IN (0,1)) NOT NULL                   -- 逻辑删除
);


COMMENT ON TABLE EMPLOYMENT_TABLE IS '录用表';
COMMENT ON COLUMN EMPLOYMENT_TABLE.EMPLOYMENT_ID IS '编号';
COMMENT ON COLUMN EMPLOYMENT_TABLE.EMPLOYMENT_STATE IS '状态 0:待入职 1:已入职 2：淘汰';
COMMENT ON COLUMN EMPLOYMENT_TABLE.RESUME_ID  IS '编号';
COMMENT ON COLUMN EMPLOYMENT_TABLE.REMARKS IS '备注';
COMMENT ON COLUMN EMPLOYMENT_TABLE.EMPLOYMENT_HIREDATE IS '录用时间';
COMMENT ON COLUMN EMPLOYMENT_TABLE.EMPLOYMENT_SALARY IS '试用工资';
COMMENT ON COLUMN EMPLOYMENT_TABLE.EMPLOYMENT_SALARYZ IS '正式工资';
COMMENT ON COLUMN EMPLOYMENT_TABLE.WAIVE_REASON IS '放弃原因';
COMMENT ON COLUMN EMPLOYMENT_TABLE.CREATED_TIME IS '创建时间';
COMMENT ON COLUMN EMPLOYMENT_TABLE.UPDATED_TIME IS '修改时间';
COMMENT ON COLUMN EMPLOYMENT_TABLE.REVISION IS '乐观锁';
COMMENT ON COLUMN EMPLOYMENT_TABLE.IS_DELETED IS '逻辑删除;1表示删除，0 表示未删除';



/*创建自增序列*/
CREATE SEQUENCE EMPLOYMENT_ID
  --最小值
MINVALUE 1     
 --不设置最大值
NOMAXVALUE      
  --从1开始计数
START WITH 1   
 --每次加1
INCREMENT BY 1 
 --一直累加，不循环
NOCYCLE 
--不建缓冲区
NOCACHE;


-- 创建招聘计划表

CREATE TABLE RECRUITMENT_PLAN(
RECRUITMENT_PLAN_ID NUMBER(10) PRIMARY KEY NOT NULL,         -- 编号
RECRUITMENT_PLAN_NAME VARCHAR2(20) NOT NULL,   -- 招聘计划名称
DEPT_ID NUMBER(10) NOT NULL,                 -- 部门编号
DEPT_POST_ID number(10) NOT NULL, -- 部门职位编号
EDUCATION_NAME VARCHAR2(20) NOT NULL,                 -- 学历名称
RECRUITMENT_PLAN_NUMBER NUMBER(10) DEFAULT 0 NOT NULL,               -- 需招聘人数
RECRUITMENT_PLAN_START_TIME DATE NOT NULL,	          -- 开始时间
RECRUITMENT_PLAN_END_TIME DATE NOT NULL,                       -- 结束时间
RECRUITMENT_PLAN_SALARY_ID NUMBER(10) NOT NULL,             -- 月薪范围编号	
RECRUITMENT_ZT number(10) DEFAULT 0 NOT NULL,   -- 招聘计划状态: 0 招聘中，1 已结束
CREATED_TIME DATE NOT NULL,                   -- 创建时间
UPDATED_TIME DATE NOT NULL,                   -- 修改时间
REVISION NUMBER(10) DEFAULT  1 NOT NULL,                 -- 乐观锁
IS_DELETED NUMBER(10) DEFAULT 0 CHECK (IS_DELETED IN (0,1)) NOT NULL                   -- 逻辑删除

);

COMMENT ON TABLE RECRUITMENT_PLAN IS '招聘计划表';
COMMENT ON COLUMN RECRUITMENT_PLAN.RECRUITMENT_PLAN_ID IS '编号';
COMMENT ON COLUMN RECRUITMENT_PLAN.RECRUITMENT_PLAN_NAME IS '招聘计划编号';
COMMENT ON COLUMN RECRUITMENT_PLAN.DEPT_ID IS '部门编号';
COMMENT ON COLUMN RECRUITMENT_PLAN.DEPT_POST_ID  IS '部门职位编号';
COMMENT ON COLUMN RECRUITMENT_PLAN.EDUCATION_NAME IS '学历名称';
COMMENT ON COLUMN RECRUITMENT_PLAN.RECRUITMENT_PLAN_NUMBER IS '需招聘人数';
COMMENT ON COLUMN RECRUITMENT_PLAN.RECRUITMENT_PLAN_START_TIME IS '开始时间';
COMMENT ON COLUMN RECRUITMENT_PLAN.RECRUITMENT_PLAN_END_TIME IS '结束时间';
COMMENT ON COLUMN RECRUITMENT_PLAN.RECRUITMENT_PLAN_SALARY_ID IS '月薪范围';
COMMENT ON COLUMN RECRUITMENT_PLAN.RECRUITMENT_ZT IS '招聘计划状态: 0 招聘中，1 已结束';
COMMENT ON COLUMN RECRUITMENT_PLAN.CREATED_TIME IS '创建时间';
COMMENT ON COLUMN RECRUITMENT_PLAN.UPDATED_TIME IS '修改时间';
COMMENT ON COLUMN RECRUITMENT_PLAN.REVISION IS '乐观锁';
COMMENT ON COLUMN RECRUITMENT_PLAN.IS_DELETED IS '逻辑删除;1表示删除，0 表示未删除';

/*创建自增序列*/
CREATE SEQUENCE RECRUITMENT_PLAN_ID
  --最小值
MINVALUE 1     
 --不设置最大值
NOMAXVALUE      
  --从1开始计数
START WITH 1   
 --每次加1
INCREMENT BY 1 
 --一直累加，不循环
NOCYCLE 
--不建缓冲区
NOCACHE;


-- 创建员工表
CREATE TABLE STAFF(
    STAFF_ID NUMBER(10) NOT NULL PRIMARY KEY,  --  员工编号
    STAFF_NAME VARCHAR2(20) NOT NULL,  --  员工姓名
    STAFF_SEX VARCHAR2(2) NOT NULL,  -- 性别
		STAFF_AGE NUMBER(10) NOT NULL, -- 年龄
    STAFF_PHONE NUMBER(11) NOT NULL,  --  手机号
    STAFF_EMAIL VARCHAR2(50) UNIQUE,  -- 邮箱
    STAFF_BIRTHDAY DATE NOT NULL,  -- 出生日期
    STAFF_OUTLOOK VARCHAR2(10) NOT NULL,  --  政治面貌
    STAFF_EDUCATION VARCHAR2(10) NOT NULL,  --  学历
    DEPT_POST_ID NUMBER(10) not null ,--部门职位编号
		WORKER_ID NUMBER(10), -- 转正编号
    STAFF_PASS VARCHAR2(100) DEFAULT 123456 NOT NULL,  -- 密码
    STAFF_HIREDATE DATE NOT NULL,   --  入职日期
    STAFF_IDENTITY VARCHAR2(28) UNIQUE,   --  身份证
    DEPT_ID NUMBER(10) NOT NULL,  --  部门编号
    STAFF_MAJOR VARCHAR2(1000),   --  专业
    STAFF_EMERGENCY NUMBER(11),  -- 紧急联系人
    STAFF_WECHAT VARCHAR2(100),  --  微信
    STAFF_QQ VARCHAR2(100),  --  QQ
    STAFF_CREDIT VARCHAR2(50),  --   银行卡号
    STAFF_BLOOD VARCHAR(10),  --  血型
    STAFF_SIGN VARCHAR2(10),  -- 星座
    STAFF_MARITAL VARCHAR2(10),  --  婚姻状态
    STAFF_REGISTERED VARCHAR2(100),  --  户口所在地
    STAFF_SCHOOL VARCHAR2(100),   --  毕业学校
    STAFF_ADDRESS VARCHAR2(100),  --  现住地址
		STAFF_STATE NUMBER(10) DEFAULT 0 NOT NULL CHECK(STAFF_STATE IN(0,1,2)), -- 员工状态 0试用 1 正式 2离职
		WORK_AGE VARCHAR2(100), -- 工龄
		WORKER_DATE DATE NOT NULL,-- 转正日期
    CREATED_TIME DATE NOT NULL,  --  创建时间
    UPDATED_TIME DATE NOT NULL,  --  修改时间
    IS_DELETED NUMBER(10) DEFAULT  0 NOT NULL CHECK (IS_DELETED IN (0,1)),  --  逻辑删除;0：未删除，1：已删除
    REVISION NUMBER(10) DEFAULT  1 NOT NULL  --  乐观锁
);

COMMENT ON TABLE STAFF IS '员工表';
COMMENT ON COLUMN STAFF.DEPT_POST_ID IS '部门职位编号外键';
COMMENT ON COLUMN STAFF.STAFF_ID IS '员工编号';
COMMENT ON COLUMN STAFF.STAFF_NAME IS '员工姓名';
COMMENT ON COLUMN STAFF.STAFF_SEX IS '性别';
COMMENT ON COLUMN STAFF.STAFF_AGE IS '年龄';
COMMENT ON COLUMN STAFF.STAFF_PHONE IS '手机号码';
COMMENT ON COLUMN STAFF.STAFF_EMAIL IS '邮箱';
COMMENT ON COLUMN STAFF.STAFF_BIRTHDAY IS '出生日期';
COMMENT ON COLUMN STAFF.STAFF_OUTLOOK IS '政治面貌';
COMMENT ON COLUMN STAFF.STAFF_EDUCATION IS '学历';
COMMENT ON COLUMN STAFF.STAFF_PASS IS '密码';
COMMENT ON COLUMN STAFF.STAFF_HIREDATE IS '入职日期';
COMMENT ON COLUMN STAFF.STAFF_IDENTITY IS '身份证';
COMMENT ON COLUMN STAFF.DEPT_ID IS '部门编号';
COMMENT ON COLUMN STAFF.WORKER_ID IS '转正编号';
COMMENT ON COLUMN STAFF.STAFF_MAJOR IS '专业';
COMMENT ON COLUMN STAFF.STAFF_EMERGENCY IS '紧急联系人';
COMMENT ON COLUMN STAFF.STAFF_WECHAT IS '微信';
COMMENT ON COLUMN STAFF.STAFF_QQ IS 'QQ';
COMMENT ON COLUMN STAFF.STAFF_CREDIT IS '银行卡号';
COMMENT ON COLUMN STAFF.STAFF_BLOOD IS '血型';
COMMENT ON COLUMN STAFF.STAFF_SIGN IS '星座';
COMMENT ON COLUMN STAFF.STAFF_MARITAL IS '婚姻状态';
COMMENT ON COLUMN STAFF.STAFF_REGISTERED IS '户口所在地';
COMMENT ON COLUMN STAFF.STAFF_SCHOOL IS '毕业学校';
COMMENT ON COLUMN STAFF.STAFF_ADDRESS IS '现住地址';
COMMENT ON COLUMN STAFF.STAFF_STATE IS '员工状态';
COMMENT ON COLUMN STAFF.WORK_AGE IS '工龄';
COMMENT ON COLUMN STAFF.CREATED_TIME IS '创建时间';
COMMENT ON COLUMN STAFF.UPDATED_TIME IS '修改时间';
COMMENT ON COLUMN STAFF.IS_DELETED IS '逻辑删除;0：未删除，1：已删除';
COMMENT ON COLUMN STAFF.REVISION IS '乐观锁';


-- 删除员工自增序列
-- DROP SEQUENCE STAFF_ID;

/*创建员工自增序列*/
CREATE SEQUENCE STAFF_ID
  --最小值
MINVALUE 1     
 --不设置最大值
NOMAXVALUE      
  --从1开始计数
START WITH 1   
 --每次加1
INCREMENT BY 1 
 --一直累加，不循环
NOCYCLE 
--不建缓冲区
NOCACHE;

-- 创建荣誉/奖励表
CREATE TABLE GLORY(
    GLORY_ID NUMBER(10) NOT NULL PRIMARY KEY,   --  荣誉/奖励编号
    GLORY_NAME VARCHAR2(20) NOT NULL,  --  荣誉/奖励名称
    STAFF_ID NUMBER(10) NOT NULL , -- 获奖人编号
    GLORY_UNITNAME VARCHAR2(100) NOT NULL,  --  颁发单位名称
    GLORY_REMARK VARCHAR2(1000),   --  备注
    CREATED_TIME DATE NOT NULL,  --   创建时间
    UPDATED_TIME DATE NOT NULL,  --  修改时间
    REVISION NUMBER(10) DEFAULT  1 NOT NULL,  --  乐观锁
    IS_DELETED NUMBER(10) DEFAULT  0 NOT NULL CHECK (IS_DELETED IN (0,1))  -- 逻辑删除;0：未删除，1：已删除
);

COMMENT ON TABLE GLORY IS '荣誉/奖励表';
COMMENT ON COLUMN GLORY.GLORY_ID IS '荣誉/奖励编号';
COMMENT ON COLUMN GLORY.GLORY_NAME IS '荣誉/奖励名称';
COMMENT ON COLUMN STAFF.STAFF_ID IS '获奖人编号';
COMMENT ON COLUMN GLORY.GLORY_UNITNAME IS '颁发单位名称';
COMMENT ON COLUMN GLORY.GLORY_REMARK IS '备注';
COMMENT ON COLUMN GLORY.CREATED_TIME IS '创建时间';
COMMENT ON COLUMN GLORY.UPDATED_TIME IS '修改时间';
COMMENT ON COLUMN GLORY.REVISION IS '乐观锁';
COMMENT ON COLUMN GLORY.IS_DELETED IS '逻辑删除;0：未删除，1：已删除';


/*创建荣誉/奖励自增序列*/
CREATE SEQUENCE GLORY_ID
  --最小值
MINVALUE 1     
 --不设置最大值
NOMAXVALUE      
  --从1开始计数
START WITH 1   
 --每次加1
INCREMENT BY 1 
 --一直累加，不循环
NOCYCLE 
--不建缓冲区
NOCACHE;

-- 创建惩罚表
CREATE TABLE PUNISH(
    PUNISH_ID NUMBER(10) NOT NULL PRIMARY KEY,   --  惩罚编号
    PUNISH_TYPE VARCHAR2(20) NOT NULL,   --  惩罚类型
    STAFF_ID NUMBER(10) NOT NULL, -- 被惩罚人编号
    PUNISH_CAUSE VARCHAR2(100),   --  惩罚原因
    PUNISH_UNIT VARCHAR2(50),   --  惩罚单位
    IS_REVOCATION NUMBER(10) DEFAULT 0 CHECK(IS_REVOCATION IN (0,1)),   --  是否撤销(0，否，1，是)
    PUNISH_REMARK VARCHAR2(1000),  --   备注
    CREATED_TIME DATE NOT NULL,  --  创建时间
    UPDATED_TIME DATE NOT NULL,   --  修改时间
    IS_DELETED NUMBER(10) DEFAULT  0 NOT NULL CHECK (IS_DELETED IN (0,1)),   --  逻辑删除;0：未删除，1：已删除
    REVISION NUMBER(10) DEFAULT  1 NOT NULL    --  乐观锁
);

COMMENT ON TABLE PUNISH IS '惩罚表';
COMMENT ON COLUMN PUNISH.PUNISH_ID IS '惩罚编号';
COMMENT ON COLUMN PUNISH.PUNISH_TYPE IS '惩罚类型';
COMMENT ON COLUMN PUNISH.STAFF_ID IS '被惩罚人编号';
COMMENT ON COLUMN PUNISH.PUNISH_CAUSE IS '惩罚原因';
COMMENT ON COLUMN PUNISH.PUNISH_UNIT IS '惩罚单位';
COMMENT ON COLUMN PUNISH.IS_REVOCATION IS '是否撤销';
COMMENT ON COLUMN PUNISH.PUNISH_REMARK IS '备注';
COMMENT ON COLUMN PUNISH.CREATED_TIME IS '创建时间';
COMMENT ON COLUMN PUNISH.UPDATED_TIME IS '修改时间';
COMMENT ON COLUMN PUNISH.IS_DELETED IS '逻辑删除;0：未删除，1：已删除';
COMMENT ON COLUMN PUNISH.REVISION IS '乐观锁';

/*创建惩罚自增序列*/
CREATE SEQUENCE PUNISH_ID
  --最小值
MINVALUE 1     
 --不设置最大值
NOMAXVALUE      
  --从1开始计数
START WITH 1   
 --每次加1
INCREMENT BY 1 
 --一直累加，不循环
NOCYCLE 
--不建缓冲区
NOCACHE;


-- 创建审批主表
CREATE TABLE AUDITFLOW(
    AUDITFLOW_ID NUMBER(10) NOT NULL PRIMARY KEY, -- 审批编号
    AUDITFLOW_TITLE VARCHAR2(50) NOT NULL, --  标题
    AUDITFLOW_TYPE VARCHAR2(50) NOT NULL, -- 审批类型
    STAFF_NAME VARCHAR2(50) NOT NULL,  --  申请人
    AUDITFLOW_STATE NUMBER(10) DEFAULT 0 CHECK (AUDITFLOW_STATE IN (0,1,2,3)) NOT NULL,  --  申请状态（0，待审，1，通过，2，驳回，3，撤销）
    CREATED_TIME DATE NOT NULL,  --  创建时间
    UPDATED_TIME DATE NOT NULL,  --  修改时间
		REVISION NUMBER(10) DEFAULT 1 NOT NULL,-- 乐观锁
    IS_DELETED NUMBER(10) DEFAULT 0 CHECK (IS_DELETED IN (0,1)) NOT NULL  --  逻辑删除,
);



COMMENT ON TABLE AUDITFLOW IS '审批主表';
COMMENT ON COLUMN AUDITFLOW.AUDITFLOW_ID IS '审批编号';
COMMENT ON COLUMN AUDITFLOW.AUDITFLOW_TITLE IS '标题';
COMMENT ON COLUMN AUDITFLOW.AUDITFLOW_TYPE IS '审批类型';
COMMENT ON COLUMN AUDITFLOW.STAFF_NAME IS '申请人';
COMMENT ON COLUMN AUDITFLOW.AUDITFLOW_STATE IS '申请状态';
COMMENT ON COLUMN AUDITFLOW.CREATED_TIME IS '创建时间';
COMMENT ON COLUMN AUDITFLOW.UPDATED_TIME IS '修改时间';
COMMENT ON COLUMN AUDITFLOW.REVISION IS '乐观锁';
COMMENT ON COLUMN AUDITFLOW.IS_DELETED IS '逻辑删除';

-- drop SEQUENCE AUDITFLOW_ID

/*创建自增序列*/
CREATE SEQUENCE AUDITFLOW_ID
  --最小值
MINVALUE 1     
 --不设置最大值
NOMAXVALUE      
  --从1开始计数
START WITH 1   
 --每次加1
INCREMENT BY 1 
 --一直累加，不循环
NOCYCLE 
--不建缓冲区
NOCACHE;


-- 创建审批明细表
CREATE TABLE AUDITFLOWDETAIL(
    AUDITFLOWDETAIL_ID NUMBER(10) PRIMARY KEY NOT NULL, -- 审批明细编号
    AUDITFLOW_ID NUMBER(10) NOT NULL,  --  审批编号
    STAFF_NAME VARCHAR2(50) NOT NULL,  --  审核人
    AUDITFLOWDETAI_REMARKS VARCHAR2(100),  --  审核备注
    AUDITFLOWDETAI_DATE DATE,  --  审核时间
    AUDITFLOWDETAI_STATE NUMBER(10) DEFAULT 0 CHECK (AUDITFLOWDETAI_STATE IN (0,1,2,3,4)) NOT NULL,  --  审核状态（0，审批中，1，待我审批，2，通过，3，驳回 4,被撤销）
    CREATED_TIME DATE NOT NULL,  --  创建时间
    UPDATED_TIME DATE NOT NULL,  --  修改时间
    REVISION NUMBER(10) DEFAULT 1 NOT NULL,-- 乐观锁
    IS_DELETED NUMBER(10) DEFAULT 0 CHECK (IS_DELETED IN (0,1)) NOT NULL --  逻辑删除
);

COMMENT ON TABLE AUDITFLOWDETAIL IS '审批流明细表';
COMMENT ON COLUMN AUDITFLOWDETAIL.AUDITFLOWDETAIL_ID IS '审批流明细编号';
COMMENT ON COLUMN AUDITFLOWDETAIL.AUDITFLOW_ID IS '审批编号';
COMMENT ON COLUMN AUDITFLOWDETAIL.STAFF_NAME IS '审核人';
COMMENT ON COLUMN AUDITFLOWDETAIL.AUDITFLOWDETAI_REMARKS IS '审核备注';
COMMENT ON COLUMN AUDITFLOWDETAIL.AUDITFLOWDETAI_DATE IS '审核时间';
COMMENT ON COLUMN AUDITFLOWDETAIL.AUDITFLOWDETAI_STATE IS '审核状态';
COMMENT ON COLUMN AUDITFLOWDETAIL.CREATED_TIME IS '创建时间';
COMMENT ON COLUMN AUDITFLOWDETAIL.UPDATED_TIME IS '修改时间';
COMMENT ON COLUMN AUDITFLOWDETAIL.REVISION IS '乐观锁';
COMMENT ON COLUMN AUDITFLOWDETAIL.IS_DELETED IS '逻辑删除';

-- drop SEQUENCE AUDITFLOWDETAIL_ID

/*创建自增序列*/
CREATE SEQUENCE AUDITFLOWDETAIL_ID
  --最小值
MINVALUE 1     
 --不设置最大值
NOMAXVALUE      
  --从1开始计数
START WITH 1   
 --每次加1
INCREMENT BY 1 
 --一直累加，不循环
NOCYCLE 
--不建缓冲区
NOCACHE;


-- 创建加班表
CREATE TABLE OVERTIMEASK(
    OVERTIMEASK_ID NUMBER(10) PRIMARY KEY NOT NULL, -- 加班表编号
    AUDITFLOW_ID NUMBER(10) NOT NULL, -- 审批编号
    STAFF_NAME VARCHAR2(50) NOT NULL,-- 员工名称
    DEPT_NAME VARCHAR2(50) NOT NULL,-- 发起人部门名称
    OVERTIMEASK_TYPE VARCHAR2(50) NOT NULL,-- 加班类型
    OVERTIMEASK_MATTER VARCHAR2(200) NOT NULL,-- 加班事由
    OVERTIMEASK_REMARKS VARCHAR2(200),-- 备注
    OVERTIMEASK_S_DATE DATE NOT NULL,-- 计划加班开始时间
    OVERTIMEASK_E_DATE DATE NOT NULL,-- 计划加班结束时间
    OVERTIMEASK_TOTAL_DATE NUMBER(10) DEFAULT 0 NOT NULL,-- 加班总小时
		OVERTIMASK_ACTUAL_TIME DATE, -- 实际打卡加班时间 
		OVERTIMASK_ACTUAL_OVERTIME DATE, -- 实际打卡结束加班时间
		OVERTIMASK_ACTUAL_TOKINAGA NUMBER(10), -- 实际加班时长
    OVERTIMEASK_STATE NUMBER(10) DEFAULT  0 CHECK (OVERTIMEASK_STATE   IN (0,1)) NOT NULL,-- 状态 0:不同意 1:同意
    OVERTIMEASK_CONDITION NUMBER(10) DEFAULT  0 CHECK (OVERTIMEASK_CONDITION   IN (0,1,2)),   -- 加班状态 0：未开始 1：进行中 2：已完成 改
		CREATED_TIME DATE NOT NULL,-- 创建时间
    UPDATED_TIME DATE NOT NULL,-- 修改时间
    REVISION NUMBER(10) DEFAULT 1 NOT NULL,-- 乐观锁
    IS_DELETED NUMBER(10) DEFAULT 0 CHECK (IS_DELETED IN (0,1)) NOT NULL --  逻辑删除
);

COMMENT ON TABLE OVERTIMEASK IS '加班表';
COMMENT ON COLUMN OVERTIMEASK.OVERTIMEASK_ID IS '加班表编号';
COMMENT ON COLUMN OVERTIMEASK.AUDITFLOW_ID IS '审批编号';
COMMENT ON COLUMN OVERTIMEASK.STAFF_NAME IS '员工名称';
COMMENT ON COLUMN OVERTIMEASK.DEPT_NAME IS '发起人部门名称';
COMMENT ON COLUMN OVERTIMEASK.OVERTIMEASK_TYPE IS '加班类型';
COMMENT ON COLUMN OVERTIMEASK.OVERTIMEASK_MATTER IS '加班事由';
COMMENT ON COLUMN OVERTIMEASK.OVERTIMEASK_REMARKS IS '备注';
COMMENT ON COLUMN OVERTIMEASK.OVERTIMEASK_S_DATE IS '加班开始时间';
COMMENT ON COLUMN OVERTIMEASK.OVERTIMEASK_E_DATE IS '加班结束时间';
COMMENT ON COLUMN OVERTIMEASK.OVERTIMEASK_TOTAL_DATE IS '加班总小时';
COMMENT ON COLUMN OVERTIMEASK.OVERTIMASK_ACTUAL_TIME IS '实际打卡加班时间';
COMMENT ON COLUMN OVERTIMEASK.OVERTIMASK_ACTUAL_OVERTIME IS '实际打卡结束加班时间';
COMMENT ON COLUMN OVERTIMEASK.OVERTIMASK_ACTUAL_TOKINAGA IS '实际加班时长';
COMMENT ON COLUMN OVERTIMEASK.OVERTIMEASK_STATE IS '状态 0:不同意 1:同意';
COMMENT ON COLUMN OVERTIMEASK.OVERTIMEASK_CONDITION IS '加班状态 0：未开始 1：已完成';
COMMENT ON COLUMN OVERTIMEASK.CREATED_TIME IS '创建时间';
COMMENT ON COLUMN OVERTIMEASK.UPDATED_TIME IS '修改时间';
COMMENT ON COLUMN OVERTIMEASK.REVISION IS '乐观锁';
COMMENT ON COLUMN OVERTIMEASK.IS_DELETED IS '逻辑删除';

-- drop SEQUENCE OVERTIMEASK_ID


/*创建自增序列*/
CREATE SEQUENCE OVERTIMEASK_ID
  --最小值
MINVALUE 1     
 --不设置最大值
NOMAXVALUE      
  --从1开始计数
START WITH 1   
 --每次加1
INCREMENT BY 1 
 --一直累加，不循环
NOCYCLE 
--不建缓冲区
NOCACHE;



-- 创建请假表
CREATE TABLE LEAVE(
    LEAVE_ID NUMBER(10) PRIMARY KEY NOT NULL,-- 请假编号
    AUDITFLOW_ID NUMBER(10) NOT NULL,-- 审批编号
    STAFF_NAME VARCHAR2(50) NOT NULL,-- 员工名称
    DEPT_NAME VARCHAR2(50) NOT NULL,-- 发起人部门名称
    LEAVE_TYPE VARCHAR2(50) NOT NULL,-- 请假类型
    LEAVE_MATTER VARCHAR2(200) NOT NULL,-- 请假事由
    LEAVE_REMARKS VARCHAR2(200),-- 备注
    LEAVE_S_DATE DATE NOT NULL,-- 请假开始时间
    LEAVE_E_DATE DATE NOT NULL,-- 请假结束时间
    LEAVE_TOTAL_DATE NUMBER(10) DEFAULT  0 NOT NULL,-- 请假总小时
    LEAVE_ACTUAL_TIME DATE, -- 实际打卡请假时间 
		LEAVE_ACTUAL_OVERTIME DATE, -- 实际打卡结束请假时间
		LEAVE_ACTUAL_TOKINAGA NUMBER(10), -- 实际请假时长
    LEAVE_STATE NUMBER(10) DEFAULT  0 CHECK (LEAVE_STATE   IN (0,1)) NOT NULL,--状态 0:不同意 1:同意
    LEAVE_CONDITION NUMBER(10) DEFAULT  0 CHECK (LEAVE_CONDITION   IN (0,1,2)),   -- 请假状态 0：未开始 1：进行中 2：已完成
    CREATED_TIME DATE NOT NULL,-- 创建时间
    UPDATED_TIME DATE NOT NULL,-- 修改时间
    REVISION NUMBER(10) DEFAULT 1 NOT NULL,-- 乐观锁
    IS_DELETED NUMBER(10) DEFAULT 0 CHECK (IS_DELETED IN (0,1)) NOT NULL --  逻辑删除
);

COMMENT ON TABLE LEAVE IS '请假表';
COMMENT ON COLUMN LEAVE.LEAVE_ID IS '请假编号';
COMMENT ON COLUMN LEAVE.AUDITFLOW_ID IS '审批编号';
COMMENT ON COLUMN LEAVE.STAFF_NAME IS '员工名称';
COMMENT ON COLUMN LEAVE.DEPT_NAME IS '发起人部门';
COMMENT ON COLUMN LEAVE.LEAVE_TYPE IS '请假类型';
COMMENT ON COLUMN LEAVE.LEAVE_MATTER IS '请假事由';
COMMENT ON COLUMN LEAVE.LEAVE_REMARKS IS '备注';
COMMENT ON COLUMN LEAVE.LEAVE_S_DATE IS '请假开始时间';
COMMENT ON COLUMN LEAVE.LEAVE_E_DATE IS '请假结束时间';
COMMENT ON COLUMN LEAVE.LEAVE_TOTAL_DATE IS '请假总小时';
COMMENT ON COLUMN LEAVE.LEAVE_STATE IS '状态 0:不同意 1:同意';
COMMENT ON COLUMN LEAVE.LEAVE_ACTUAL_TIME IS '实际打卡请假时间';
COMMENT ON COLUMN LEAVE.LEAVE_ACTUAL_OVERTIME IS '实际打结束请假时间';
COMMENT ON COLUMN LEAVE.LEAVE_ACTUAL_TOKINAGA IS '实际请假时长';
COMMENT ON COLUMN LEAVE.LEAVE_CONDITION IS '请假状态 0：未开始 1：已完成';
COMMENT ON COLUMN LEAVE.CREATED_TIME IS '创建时间';
COMMENT ON COLUMN LEAVE.UPDATED_TIME IS '修改时间';
COMMENT ON COLUMN LEAVE.REVISION IS '乐观锁';
COMMENT ON COLUMN LEAVE.IS_DELETED IS '逻辑删除';


-- drop SEQUENCE LEAVE_ID


/*创建自增序列*/
CREATE SEQUENCE LEAVE_ID
  --最小值
MINVALUE 1     
 --不设置最大值
NOMAXVALUE      
  --从1开始计数
START WITH 1   
 --每次加1
INCREMENT BY 1 
 --一直累加，不循环
NOCYCLE 
--不建缓冲区
NOCACHE;


-- 创建出差表
CREATE TABLE TRAVEL(
    TRAVEL_ID NUMBER(10) PRIMARY KEY NOT NULL,-- 出差编号
    AUDITFLOW_ID NUMBER(10) NOT NULL,-- 审批编号
    STAFF_NAME VARCHAR2(50) NOT NULL,-- 员工名称
    DEPT_NAME VARCHAR2(50) NOT NULL,-- 发起人部门名称
    TRAVEL_PLACE VARCHAR2(50) NOT NULL,-- 出差地点
    TRAVEL_MATTER VARCHAR2(200) NOT NULL,-- 出差事由
    TRAVEL_S_DATE DATE NOT NULL,-- 出差开始时间
    TRAVEL_E_DATE DATE NOT NULL,-- 出差结束时间
    TRAVEL_TOTAL_DATE NUMBER(10) DEFAULT  0 NOT NULL,-- 出差总小时
    TRAVEL_ACTUAL_TIME DATE, -- 实际打卡出差时间 
		TRAVEL_ACTUAL_OVERTIME DATE, -- 实际打卡结束出差时间
		TRAVEL_ACTUAL_TOKINAGA NUMBER(10), -- 实际出差时长
    TRAVEL_STATE NUMBER(10) DEFAULT  0 CHECK (TRAVEL_STATE   IN (0,1)) NOT NULL,--状态 0:不同意 1:同意
    TRAVEL_CONDITION NUMBER(10) DEFAULT  0 CHECK (TRAVEL_CONDITION   IN (0,1,2)),   -- 出差状态 0：未开始 1：进行中 2：已完成
    CREATED_TIME DATE NOT NULL,-- 创建时间
    UPDATED_TIME DATE NOT NULL,-- 修改时间
    REVISION NUMBER(10) DEFAULT 1 NOT NULL,-- 乐观锁
    IS_DELETED NUMBER(10) DEFAULT 0 CHECK (IS_DELETED IN (0,1)) NOT NULL --  逻辑删除
);

COMMENT ON TABLE TRAVEL IS '出差表';
COMMENT ON COLUMN TRAVEL.TRAVEL_ID IS '出差编号';
COMMENT ON COLUMN TRAVEL.AUDITFLOW_ID IS '审批编号';
COMMENT ON COLUMN TRAVEL.STAFF_NAME IS '员工名称';
COMMENT ON COLUMN TRAVEL.DEPT_NAME IS '发起人部门';
COMMENT ON COLUMN TRAVEL.TRAVEL_PLACE IS '出差地点';
COMMENT ON COLUMN TRAVEL.TRAVEL_MATTER IS '出差事由';
COMMENT ON COLUMN TRAVEL.TRAVEL_S_DATE IS '出差开始时间';
COMMENT ON COLUMN TRAVEL.TRAVEL_E_DATE IS '出差结束时间';
COMMENT ON COLUMN TRAVEL.TRAVEL_TOTAL_DATE IS '出差总时长';
COMMENT ON COLUMN TRAVEL.TRAVEL_STATE IS '状态 0:不同意 1:同意';
COMMENT ON COLUMN TRAVEL.TRAVEL_ACTUAL_TIME IS '实际打卡出差时间';
COMMENT ON COLUMN TRAVEL.TRAVEL_ACTUAL_OVERTIME IS '实际打卡结束出差时间';
COMMENT ON COLUMN TRAVEL.TRAVEL_ACTUAL_TOKINAGA IS '实际出差时长';
COMMENT ON COLUMN TRAVEL.TRAVEL_CONDITION IS '出差状态 0：未开始 1：已完成';
COMMENT ON COLUMN TRAVEL.CREATED_TIME IS '创建时间';
COMMENT ON COLUMN TRAVEL.UPDATED_TIME IS '修改时间';
COMMENT ON COLUMN TRAVEL.REVISION IS '乐观锁';
COMMENT ON COLUMN TRAVEL.IS_DELETED IS '逻辑删除';


-- drop SEQUENCE TRAVEL_ID


/*创建自增序列*/
CREATE SEQUENCE TRAVEL_ID
  --最小值
MINVALUE 1     
 --不设置最大值
NOMAXVALUE      
  --从1开始计数
START WITH 1   
 --每次加1
INCREMENT BY 1 
 --一直累加，不循环
NOCYCLE 
--不建缓冲区
NOCACHE;


-- 创建离职表
CREATE TABLE QUIT(
    QUIT_ID NUMBER(10) PRIMARY KEY NOT NULL, -- 离职编号
    AUDITFLOW_ID NUMBER(10),-- 审批编号
    STAFF_NAME VARCHAR2(50) NOT NULL,-- 员工名称
    DEPT_NAME VARCHAR2(50),-- 发起人部门名称
    QUIT_TYPE VARCHAR2(50) NOT NULL,-- 离职类型
    QUIT_EXPLAIN VARCHAR2(200) NOT NULL,-- 离职说明
    QUIT_STATE NUMBER(10) DEFAULT  0 CHECK (QUIT_STATE  IN (0,1))  NOT NULL,--状态 0:不同意 1:同意
    APPLY_QUIT_DATE DATE,-- 申请离职日期
    FORMAL_QUIT_DATE DATE,-- 正式离职日期
    CREATED_TIME DATE NOT NULL,-- 创建时间
    UPDATED_TIME DATE NOT NULL,-- 修改时间
    REVISION NUMBER(10) DEFAULT 1 NOT NULL,-- 乐观锁
    IS_DELETED NUMBER(10) DEFAULT 0 CHECK (IS_DELETED IN (0,1)) NOT NULL --  逻辑删除
);

COMMENT ON TABLE QUIT IS '离职表';
COMMENT ON COLUMN QUIT.QUIT_ID IS '离职编号';
COMMENT ON COLUMN QUIT.AUDITFLOW_ID IS '审批编号';
COMMENT ON COLUMN QUIT.STAFF_NAME IS '员工名称';
COMMENT ON COLUMN QUIT.DEPT_NAME IS '发起人部门名称';
COMMENT ON COLUMN QUIT.QUIT_TYPE IS '离职类型';
COMMENT ON COLUMN QUIT.QUIT_EXPLAIN IS '离职说明';
COMMENT ON COLUMN QUIT.APPLY_QUIT_DATE IS '申请离职日期';
COMMENT ON COLUMN QUIT.QUIT_STATE IS '状态 0:不同意 1:同意';
COMMENT ON COLUMN QUIT.FORMAL_QUIT_DATE IS '正式离职日期';
COMMENT ON COLUMN QUIT.CREATED_TIME IS '创建时间';
COMMENT ON COLUMN QUIT.UPDATED_TIME IS '修改时间';
COMMENT ON COLUMN QUIT.REVISION IS '乐观锁';
COMMENT ON COLUMN QUIT.IS_DELETED IS '逻辑删除';

-- drop SEQUENCE QUIT_ID


/*创建自增序列*/
CREATE SEQUENCE QUIT_ID
  --最小值
MINVALUE 1     
 --不设置最大值
NOMAXVALUE      
  --从1开始计数
START WITH 1   
 --每次加1
INCREMENT BY 1 
 --一直累加，不循环
NOCYCLE 
--不建缓冲区
NOCACHE;

-- 创建转正表
CREATE TABLE WORKER(
    WORKER_ID NUMBER(10) PRIMARY KEY NOT NULL, -- 转正编号
    AUDITFLOW_ID NUMBER(10),-- 审批编号
    STAFF_NAME VARCHAR2(50) NOT NULL,-- 员工名称
    DEPT_NAME VARCHAR2(50),-- 发起人部门名称
    WORKER_TYPE VARCHAR2(50) NOT NULL,-- 转正类型
    WORKER_REMARKS VARCHAR2(200),-- 备注
    WORKER_STATE NUMBER(10) DEFAULT  0 CHECK (WORKER_STATE  IN (0,1)) NOT NULL,--状态 0:不同意 1:同意
    WORKER_DATE DATE NOT NULL,-- 转正日期
    CREATED_TIME DATE NOT NULL,-- 创建时间
    UPDATED_TIME DATE NOT NULL,-- 修改时间
    REVISION NUMBER(10) DEFAULT 1 NOT NULL,-- 乐观锁
    IS_DELETED NUMBER(10) DEFAULT 0 CHECK (IS_DELETED IN (0,1)) NOT NULL --  逻辑删除
);

COMMENT ON TABLE WORKER IS '转正';
COMMENT ON COLUMN WORKER.WORKER_ID IS '转正编号';
COMMENT ON COLUMN WORKER.AUDITFLOW_ID IS '审批编号';
COMMENT ON COLUMN WORKER.STAFF_NAME IS '员工名称';
COMMENT ON COLUMN WORKER.DEPT_NAME IS '部门编号';
COMMENT ON COLUMN WORKER.WORKER_TYPE IS '转正类型';
COMMENT ON COLUMN WORKER.WORKER_REMARKS IS '备注';
COMMENT ON COLUMN WORKER.WORKER_DATE IS '转正日期';
COMMENT ON COLUMN WORKER.WORKER_STATE IS '状态 0:不同意 1:同意';
COMMENT ON COLUMN WORKER.CREATED_TIME IS '创建时间';
COMMENT ON COLUMN WORKER.UPDATED_TIME IS '修改时间';
COMMENT ON COLUMN WORKER.REVISION IS '乐观锁';
COMMENT ON COLUMN WORKER.IS_DELETED IS '逻辑删除';


-- drop SEQUENCE WORKER_ID

/*创建自增序列*/
CREATE SEQUENCE WORKER_ID
  --最小值
MINVALUE 1     
 --不设置最大值
NOMAXVALUE      
  --从1开始计数
START WITH 1   
 --每次加1
INCREMENT BY 1 
 --一直累加，不循环
NOCYCLE 
--不建缓冲区
NOCACHE;

-- 创建调薪表
CREATE TABLE SALARY(
    SALARY_ID NUMBER(10) PRIMARY KEY NOT NULL, -- 调薪编号
    AUDITFLOW_ID NUMBER(10),-- 审批编号
    STAFF_NAME VARCHAR2(50) NOT NULL,-- 员工名称
     DEPT_NAME VARCHAR2(50),-- 发起人部门名称
    FRONT_SALARY NUMBER(10,2) NOT NULL,-- 调薪前基本工资
    AFTER_SALARY NUMBER(10,2) NOT NULL,-- 调薪后基本工资
		operator VARCHAR(20),--操作人
    SALARY_REMARKS VARCHAR2(200),-- 备注
		SALARY_TYPE VARCHAR2(200), --调薪原因
    SALARY_STATE NUMBER(10) DEFAULT  0 CHECK (SALARY_STATE  IN (0,1))  NOT NULL,--状态 0:不同意 1:同意
    TAKE_EFFECT_DATE DATE NOT NULL,-- 生效日期
    CREATED_TIME DATE NOT NULL,-- 创建时间
    UPDATED_TIME DATE NOT NULL,-- 修改时间
    REVISION NUMBER(10) DEFAULT 1 NOT NULL,-- 乐观锁
    IS_DELETED NUMBER(10) DEFAULT 0 CHECK (IS_DELETED IN (0,1)) NOT NULL --  逻辑删除
);

COMMENT ON TABLE SALARY IS '调薪表';
COMMENT ON COLUMN SALARY.SALARY_ID IS '调薪编号';
COMMENT ON COLUMN SALARY.AUDITFLOW_ID IS '审批编号';
COMMENT ON COLUMN SALARY.STAFF_NAME IS '员工名称';
COMMENT ON COLUMN SALARY.DEPT_NAME IS '部门编号';
COMMENT ON COLUMN SALARY.FRONT_SALARY IS '调薪前基本工资';
COMMENT ON COLUMN SALARY.AFTER_SALARY IS '调薪后基本工资';
COMMENT ON COLUMN SALARY.operator IS '操作人';
COMMENT ON COLUMN SALARY.SALARY_STATE IS '状态 0:不同意 1:同意';
COMMENT ON COLUMN SALARY.SALARY_REMARKS IS '备注';
COMMENT ON COLUMN SALARY.TAKE_EFFECT_DATE IS '生效日期';
COMMENT ON COLUMN SALARY.CREATED_TIME IS '创建时间';
COMMENT ON COLUMN SALARY.UPDATED_TIME IS '修改时间';
COMMENT ON COLUMN SALARY.REVISION IS '乐观锁';
COMMENT ON COLUMN SALARY.IS_DELETED IS '逻辑删除';

-- drop SEQUENCE SALARY_ID

/*创建自增序列*/
CREATE SEQUENCE SALARY_ID
  --最小值
MINVALUE 1     
 --不设置最大值
NOMAXVALUE      
  --从1开始计数
START WITH 1   
 --每次加1
INCREMENT BY 1 
 --一直累加，不循环
NOCYCLE 
--不建缓冲区
NOCACHE;



-- 创建补打卡表
CREATE TABLE CARD(
    CARD_ID NUMBER(10) PRIMARY KEY NOT NULL, -- 补打卡编号
    AUDITFLOW_ID NUMBER(10) NOT NULL,-- 审批编号
    STAFF_NAME VARCHAR2(50) NOT NULL,-- 员工名称
    CARD_TYPE VARCHAR2(50) NOT NULL,-- 补打卡类型
    CARD_DATE DATE NOT NULL,-- 补打卡时间
    CARD_REMARKS VARCHAR(200), -- 备注
    CARD_STATE NUMBER(10) DEFAULT  0 CHECK (CARD_STATE  IN (0,1))  NOT NULL,--状态 0:不同意 1:同意
    CREATED_TIME DATE NOT NULL,-- 创建时间
    UPDATED_TIME DATE NOT NULL,-- 修改时间
    REVISION NUMBER(10) DEFAULT 1 NOT NULL,-- 乐观锁
    IS_DELETED NUMBER(10) DEFAULT 0 CHECK (IS_DELETED IN (0,1)) NOT NULL --  逻辑删除
);

COMMENT ON TABLE CARD IS '补打卡表';
COMMENT ON COLUMN CARD.CARD_ID IS '补打卡编号';
COMMENT ON COLUMN CARD.AUDITFLOW_ID IS '审批编号';
COMMENT ON COLUMN CARD.STAFF_NAME IS '员工名称';
COMMENT ON COLUMN CARD.CARD_TYPE IS '补打卡类型';
COMMENT ON COLUMN CARD.CARD_DATE IS '补打卡时间';
COMMENT ON COLUMN CARD.CARD_REMARKS IS '备注';
COMMENT ON COLUMN CARD.CARD_STATE IS '状态 0:不同意 1:同意';
COMMENT ON COLUMN CARD.CREATED_TIME IS '创建时间';
COMMENT ON COLUMN CARD.UPDATED_TIME IS '修改时间';
COMMENT ON COLUMN CARD.REVISION IS '乐观锁';
COMMENT ON COLUMN CARD.IS_DELETED IS '逻辑删除';

-- drop SEQUENCE CARD_ID


/*创建自增序列*/
CREATE SEQUENCE CARD_ID
  --最小值
MINVALUE 1     
 --不设置最大值
NOMAXVALUE      
  --从1开始计数
START WITH 1   
 --每次加1
INCREMENT BY 1 
 --一直累加，不循环
NOCYCLE 
--不建缓冲区
NOCACHE;



-- 创建调动记录表
CREATE TABLE TRANSFER(
    TRANSFER_ID NUMBER(10) NOT NULL PRIMARY KEY,    --  调动记录编号
    AUDITFLOW_ID NUMBER(10),-- 审批编号
		STAFF_NAME VARCHAR2(50) NOT NULL,-- 员工名称
    TRANSFER_TYPE VARCHAR2(50) NOT NULL,  --  异动类型
    CREATED_DEPT_NAME VARCHAR2(50) NOT NULL,  --  原部门名称
    TRANSFER_STATE NUMBER(10) DEFAULT  0 CHECK (TRANSFER_STATE  IN (0,1)) NOT NULL,-- 状态 0:不同意 1:同意
    UPDATED_DEPT_NAME VARCHAR2(50) NOT NULL,  --  变动后部门名称
		transfer_rawpost_NAME VARCHAR2(50),  --  原部门职位名称
    transfer_afterpost_NAME VARCHAR2(50),  --  变动后部门职位名称    
    TAKE_EFFECT_DATE DATE NOT NULL,-- 生效日期
		TRANSFER_REMARK VARCHAR(1000), -- 备注
    CREATED_TIME DATE NOT NULL,-- 创建时间 精确到秒
    UPDATED_TIME DATE NOT NULL,-- 修改时间 精确到秒
   REVISION NUMBER(10) DEFAULT  1 NOT NULL,-- 乐观锁
   IS_DELETED NUMBER(10) DEFAULT 0 CHECK(IS_DELETED IN(0,1))-- 逻辑删除 0:未删 1:已删  
);

COMMENT ON TABLE TRANSFER IS '调动记录表';
COMMENT ON COLUMN TRANSFER.TRANSFER_ID IS '调动记录编号';
COMMENT ON COLUMN TRANSFER.AUDITFLOW_ID IS '审批编号';
COMMENT ON COLUMN TRANSFER.STAFF_NAME IS '员工名称';
COMMENT ON COLUMN TRANSFER.TRANSFER_TYPE IS '异动类型';
COMMENT ON COLUMN TRANSFER.TRANSFER_STATE IS '状态 0:不同意 1:同意';
COMMENT ON COLUMN TRANSFER.CREATED_DEPT_NAME IS '原部门名称';
COMMENT ON COLUMN TRANSFER.UPDATED_DEPT_NAME IS '变动后部门名称';
COMMENT ON COLUMN TRANSFER.transfer_rawpost_NAME IS '原部门职位名称';
COMMENT ON COLUMN TRANSFER.transfer_afterpost_NAME IS '变动后部门职位名称';
COMMENT ON COLUMN TRANSFER.TAKE_EFFECT_DATE IS '生效日期';
COMMENT ON COLUMN TRANSFER.TRANSFER_REMARK IS '备注';
COMMENT ON COLUMN TRANSFER.CREATED_TIME IS '创建时间';
COMMENT ON COLUMN TRANSFER.UPDATED_TIME IS '修改时间';
COMMENT ON COLUMN TRANSFER.REVISION IS '乐观锁';
COMMENT ON COLUMN TRANSFER.IS_DELETED IS '逻辑删除 0:未删 1:已删 ';

-- drop SEQUENCE TRANSFER_ID


/*创建调动记录自增序列*/
CREATE SEQUENCE TRANSFER_ID
  --最小值
MINVALUE 1     
 --不设置最大值
NOMAXVALUE      
  --从1开始计数
START WITH 1   
 --每次加1
INCREMENT BY 1 
 --一直累加，不循环
NOCYCLE 
--不建缓冲区
NOCACHE;



-- 改 大改	
-- 新建考勤表
CREATE TABLE ATTENDANCE_SHEET (
	ATTENDANCE_SHEET_ID NUMBER (10) PRIMARY KEY NOT NULL, -- 考勤编号
	CLOCK_RECORD_ID NUMBER (10) NOT NULL,-- 打卡记录编号
	CLASSES_ID NUMBER (10),-- 班次方案编号
	CHECK_DEDUCT_ID NUMBER (10),-- 考勤扣款编号
	REVISION NUMBER (10) DEFAULT 1 NOT NULL,-- 乐观锁
	CREATED_TIME DATE NOT NULL,-- 创建时间
	UPDATED_TIME DATE NOT NULL,-- 修改时间
	IS_DELETED NUMBER (10) DEFAULT 0 CHECK ( IS_DELETED IN ( 0, 1 ) ) NOT NULL  --  逻辑删除
);
COMMENT ON TABLE ATTENDANCE_SHEET IS '考勤表';
COMMENT ON COLUMN ATTENDANCE_SHEET.ATTENDANCE_SHEET_ID IS '考勤编号';
COMMENT ON COLUMN ATTENDANCE_SHEET.CLOCK_RECORD_ID IS '打卡记录编号';
COMMENT ON COLUMN ATTENDANCE_SHEET.CHECK_DEDUCT_ID IS '考勤扣款编号';
COMMENT ON COLUMN ATTENDANCE_SHEET.CLASSES_ID IS '班次方案编号';
COMMENT ON COLUMN ATTENDANCE_SHEET.REVISION IS '乐观锁';
COMMENT ON COLUMN ATTENDANCE_SHEET.IS_DELETED IS '逻辑删除';
COMMENT ON COLUMN ATTENDANCE_SHEET.CREATED_TIME IS '创建时间';
COMMENT ON COLUMN ATTENDANCE_SHEET.UPDATED_TIME IS '修改时间';

/*创建自增序列*/
CREATE SEQUENCE ATTENDANCE_SHEET_ID
  --最小值
MINVALUE 1     
 --不设置最大值
NOMAXVALUE      
  --从1开始计数
START WITH 1   
 --每次加1
INCREMENT BY 1 
 --一直累加，不循环
NOCYCLE 
--不建缓冲区
NOCACHE;


-- 新建打卡记录表 
CREATE TABLE CLOCK_RECORD(
    CLOCK_RECORD_ID NUMBER(10)  PRIMARY KEY NOT NULL, -- 打卡记录编号
    STAFF_NAME VARCHAR2(20) NOT NULL,-- 员工名称 改
    DEPT_NAME VARCHAR2(20) NOT NULL,-- 部门名称 改
    MORN_CLOCK DATE ,-- 早上打卡时间
    AFTERNOON_CLOCK DATE ,-- 下午打卡时间
		CHECK_STATE VARCHAR2 (20),-- 考勤状态（正常、旷工、迟到、早退）改动
    REVISION NUMBER(10) DEFAULT 1 NOT NULL,-- 乐观锁
    IS_DELETED NUMBER(10) DEFAULT  0 CHECK ( IS_DELETED IN ( 0, 1 ) ) NOT NULL,-- 逻辑删除
    CREATED_TIME DATE NOT NULL,-- 创建时间
    UPDATED_TIME DATE NOT NULL -- 修改时间
);

COMMENT ON TABLE CLOCK_RECORD IS '打卡记录表';
COMMENT ON COLUMN CLOCK_RECORD.CLOCK_RECORD_ID IS '打卡记录编号';
COMMENT ON COLUMN CLOCK_RECORD.STAFF_NAME IS '员工名称';
COMMENT ON COLUMN CLOCK_RECORD.DEPT_NAME IS '部门名称';
COMMENT ON COLUMN CLOCK_RECORD.MORN_CLOCK IS '早上打卡时间';
COMMENT ON COLUMN CLOCK_RECORD.AFTERNOON_CLOCK IS '下午打卡时间';
COMMENT ON COLUMN CLOCK_RECORD.CHECK_STATE IS '考勤状态';
COMMENT ON COLUMN CLOCK_RECORD.REVISION IS '乐观锁';
COMMENT ON COLUMN CLOCK_RECORD.IS_DELETED IS '逻辑删除';
COMMENT ON COLUMN CLOCK_RECORD.CREATED_TIME IS '创建时间';
COMMENT ON COLUMN CLOCK_RECORD.UPDATED_TIME IS '修改时间';

-- drop SEQUENCE CLOCK_RECORD_ID

/*创建自增序列*/
CREATE SEQUENCE CLOCK_RECORD_ID
  --最小值
MINVALUE 1     
 --不设置最大值
NOMAXVALUE      
  --从1开始计数
START WITH 1   
 --每次加1
INCREMENT BY 1 
 --一直累加，不循环
NOCYCLE 
--不建缓冲区
NOCACHE;



-- 新建班次方案表
CREATE TABLE CLASSES(
    CLASSES_ID NUMBER(10) PRIMARY KEY NOT NULL, -- 班次编号
    CLASSES_NAME VARCHAR2(20) NOT NULL, -- 班次名称
    CLASSES_BEGIN_DATE DATE NOT NULL, -- 上班时间
    CLASSES_END_DATE DATE NOT NULL, -- 下班时间
    CLASSES_STATE NUMBER(10) DEFAULT  1 CHECK ( CLASSES_STATE IN ( 0, 1 ) ) NOT NULL, -- 状态（0，启用，1，禁用） 改动 默认改为1
    REVISION NUMBER(10) DEFAULT  1  NOT NULL, -- 乐观锁
    IS_DELETED NUMBER(10) DEFAULT  0 CHECK ( IS_DELETED IN ( 0, 1 ) ) NOT NULL, -- 逻辑删除
    CREATED_TIME DATE NOT NULL,-- 创建时间
    UPDATED_TIME DATE NOT NULL -- 修改时间
);

COMMENT ON TABLE CLASSES IS '班次方案表';
COMMENT ON COLUMN CLASSES.CLASSES_ID IS '班次编号';
COMMENT ON COLUMN CLASSES.CLASSES_NAME IS '班次名称';
COMMENT ON COLUMN CLASSES.CLASSES_BEGIN_DATE IS '上班时间';
COMMENT ON COLUMN CLASSES.CLASSES_END_DATE IS '下班时间';
COMMENT ON COLUMN CLASSES.CLASSES_STATE IS '状态';
COMMENT ON COLUMN CLASSES.REVISION IS '乐观锁';
COMMENT ON COLUMN CLASSES.IS_DELETED IS '逻辑删除';
COMMENT ON COLUMN CLASSES.CREATED_TIME IS '创建时间';
COMMENT ON COLUMN CLASSES.UPDATED_TIME IS '修改时间';


/*创建自增序列*/
CREATE SEQUENCE CLASSES_ID
  --最小值
MINVALUE 1     
 --不设置最大值
NOMAXVALUE      
  --从1开始计数
START WITH 1   
 --每次加1
INCREMENT BY 1 
 --一直累加，不循环
NOCYCLE 
--不建缓冲区
NOCACHE;

-- 创建考勤归档表
CREATE TABLE ARCHIVE(
    ARCHIVE_ID NUMBER(10) PRIMARY KEY NOT NULL, -- 归档编号
		ARCHIVE_NAME VARCHAR2(20) NOT NULL,-- 考勤归档名称
    STAFF_NAME VARCHAR2(20) NOT NULL,-- 员工名称
    DEPT_NAME VARCHAR2(20) NOT NULL,-- 部门名称
    NORMAL_FREQUENCY NUMBER(10) DEFAULT  0 NOT NULL,-- 正常次数
    LATE_FREQUENCY NUMBER(10) DEFAULT  0 NOT NULL,-- 迟到次数
    ABSENTEEISM_FREQUENCY NUMBER(10) NOT NULL,-- 旷工次数
    LEAVE_EARLY_FREQUENCY NUMBER(10) DEFAULT  0 NOT NULL,-- 早退次数
    PRESENT VARCHAR2(10) DEFAULT  0 NOT NULL,-- 是否全勤
		ATTENDANCE_DAYS NUMBER(10),--应出勤天数
    REVISION NUMBER(10) DEFAULT  1  NOT NULL,--乐观锁
    IS_DELETED NUMBER(10) DEFAULT  0 CHECK ( IS_DELETED IN ( 0, 1 ) ) NOT NULL,--逻辑删除
    CREATED_TIME DATE NOT NULL,--创建时间
    UPDATED_TIME DATE NOT NULL--修改时间
);

COMMENT ON TABLE ARCHIVE IS '月报表归档表';
COMMENT ON COLUMN ARCHIVE.ARCHIVE_ID IS '归档编号';
COMMENT ON COLUMN ARCHIVE.STAFF_NAME IS '员工名称';
COMMENT ON COLUMN ARCHIVE.ARCHIVE_NAME IS '考勤归档名称';
COMMENT ON COLUMN ARCHIVE.DEPT_NAME IS '部门名称';
COMMENT ON COLUMN ARCHIVE.NORMAL_FREQUENCY IS '正常次数';
COMMENT ON COLUMN ARCHIVE.LATE_FREQUENCY IS '迟到次数';
COMMENT ON COLUMN ARCHIVE.ABSENTEEISM_FREQUENCY IS '旷工次数';
COMMENT ON COLUMN ARCHIVE.LEAVE_EARLY_FREQUENCY IS '早退次数';
COMMENT ON COLUMN ARCHIVE.PRESENT IS '是否全勤';
COMMENT ON COLUMN ARCHIVE.ATTENDANCE_DAYS IS '应出勤天数';
COMMENT ON COLUMN CLASSES.REVISION IS '乐观锁';
COMMENT ON COLUMN CLASSES.IS_DELETED IS '逻辑删除';
COMMENT ON COLUMN CLASSES.CREATED_TIME IS '创建时间';
COMMENT ON COLUMN CLASSES.UPDATED_TIME IS '修改时间';

-- drop SEQUENCE ARCHIVE_ID

/*创建自增序列*/
CREATE SEQUENCE ARCHIVE_ID
  --最小值
MINVALUE 1     
 --不设置最大值
NOMAXVALUE      
  --从1开始计数
START WITH 1   
 --每次加1
INCREMENT BY 1 
 --一直累加，不循环
NOCYCLE 
--不建缓冲区
NOCACHE;


-- 创建加班方案表
CREATE TABLE WORKSCHEME(
    WORKSCHEME_ID NUMBER(10) NOT NULL PRIMARY KEY,    -- 加班方案编号
    WORKSCHEME_NAME VARCHAR2(50) NOT NULL,   --  加班方案名称
    WORKSCHEME_HOLIDAYRATIO NUMBER(10) NOT NULL,  --  节假日加班比例
    WORKSCHEME_DAYOFFRATIO NUMBER(10) NOT NULL,  --  休息日加班比例
    WORKSCHEME_WORKRATIO NUMBER(10) NOT NULL,  --  工作日加班比例
    WORKSCHEME_STATE NUMBER(10) DEFAULT  0 NOT NULL CHECK (WORKSCHEME_STATE IN (0,1)),  -- 状态;0：启用，1：禁用
    WORKSCHEME_REMARK VARCHAR2(1000),  --  备注
		DEPT_NAME VARCHAR2(200), -- 适用对象jiade
    CREATED_TIME DATE NOT NULL,   --  创建时间
    UPDATED_TIME DATE NOT NULL,   --  修改时间
    IS_DELETED NUMBER(10) DEFAULT  0 NOT NULL CHECK (IS_DELETED IN (0,1)),  --  逻辑删除;0：未删除，1：已删除
    REVISION NUMBER(10) DEFAULT  1 NOT NULL  --  乐观锁
);

COMMENT ON TABLE WORKSCHEME IS '加班方案表';
COMMENT ON COLUMN WORKSCHEME.WORKSCHEME_ID IS '加班方案编号';
COMMENT ON COLUMN WORKSCHEME.WORKSCHEME_NAME IS '加班方案名称';
COMMENT ON COLUMN WORKSCHEME.WORKSCHEME_HOLIDAYRATIO IS '节假日加班比例';
COMMENT ON COLUMN WORKSCHEME.WORKSCHEME_DAYOFFRATIO IS '休息日加班比例';
COMMENT ON COLUMN WORKSCHEME.WORKSCHEME_WORKRATIO IS '工作日加班比例';
COMMENT ON COLUMN WORKSCHEME.WORKSCHEME_STATE IS '状态;0：启用，1：禁用';
COMMENT ON COLUMN WORKSCHEME.WORKSCHEME_REMARK IS '备注';
COMMENT ON COLUMN WORKSCHEME.CREATED_TIME IS '创建时间';
COMMENT ON COLUMN WORKSCHEME.UPDATED_TIME IS '修改时间';
COMMENT ON COLUMN WORKSCHEME.IS_DELETED IS '逻辑删除;0：未删除，1：已删除';
COMMENT ON COLUMN WORKSCHEME.REVISION IS '乐观锁';

/*创建加班方案自增序列*/
CREATE SEQUENCE WORKSCHEME_ID
  --最小值
MINVALUE 1     
 --不设置最大值
NOMAXVALUE      
  --从1开始计数
START WITH 1   
 --每次加1
INCREMENT BY 1 
 --一直累加，不循环
NOCYCLE 
--不建缓冲区
NOCACHE;

--创建加班适用对象表
CREATE TABLE WORKSUITABLE(
    WORKSUITABLE_ID NUMBER(10) NOT NULL PRIMARY KEY,   --  加班适用对象编号
    WORKSCHEME_ID NUMBER(10) NOT NULL,  --  加班方案编号
    DEPT_ID NUMBER(10) NOT NULL,  --  部门编号
    CREATED_TIME DATE NOT NULL,  --  创建时间
    UPDATED_TIME DATE NOT NULL,  --  修改时间
    IS_DELETED NUMBER(10) DEFAULT  0 NOT NULL CHECK (IS_DELETED IN (0,1)),  --  逻辑删除;0：未删除，1：已删除
    REVISION NUMBER(10) DEFAULT  1 NOT NULL  --  乐观锁
);

COMMENT ON TABLE WORKSUITABLE IS '加班适用对象表';
COMMENT ON COLUMN WORKSUITABLE.WORKSUITABLE_ID IS '加班适用对象编号';
COMMENT ON COLUMN WORKSUITABLE.WORKSCHEME_ID IS '加班方案编号';
COMMENT ON COLUMN WORKSUITABLE.DEPT_ID IS '部门编号';
COMMENT ON COLUMN WORKSUITABLE.CREATED_TIME IS '创建时间';
COMMENT ON COLUMN WORKSUITABLE.UPDATED_TIME IS '修改时间';
COMMENT ON COLUMN WORKSUITABLE.IS_DELETED IS '逻辑删除;0：未删除，1：已删除';
COMMENT ON COLUMN WORKSUITABLE.REVISION IS '乐观锁';


/*创建加班适用对象自增序列*/
CREATE SEQUENCE WORKSUITABLE_ID
  --最小值
MINVALUE 1     
 --不设置最大值
NOMAXVALUE      
  --从1开始计数
START WITH 1   
 --每次加1
INCREMENT BY 1 
 --一直累加，不循环
NOCYCLE 
--不建缓冲区
NOCACHE;

-- 创建固定工资表
CREATE TABLE FIXEDWAGE(
    FIXEDWAGE_ID NUMBER(10) NOT NULL PRIMARY KEY,  --  固定工资编号
    FIXEDWAGE_PERIODMONEY NUMBER(10,2) DEFAULT 0 NOT NULL,  --  试用期基本工资
    STAFF_ID NUMBER(10),  --  员工编号
		STAFF_NAME VARCHAR2(20) NOT NULL UNIQUE,  --  员工姓名
    FIXEDWAGE_OFFICIALMONEY NUMBER(10,2) DEFAULT 0 NOT NULL,  --  正式期基本工资
    FIXEDWAGE_PERIODPOSTMONEY NUMBER(10,2) DEFAULT 0 NOT NULL,  -- 试用期岗位工资
    FIXEDWAGE_OFFLCIALPOSTMONEY NUMBER(10,2) DEFAULT 0 NOT NULL,  --  正式期岗位工资
    FIXEDWAGE_REMARK VARCHAR2(1000),  --  备注
    CREATED_TIME DATE NOT NULL,  --  创建时间
    UPDATED_TIME DATE NOT NULL,  -- 修改时间
    REVISION NUMBER(10) DEFAULT  1 NOT NULL,   --  乐观锁
		IS_DELETED NUMBER(10) DEFAULT  0 NOT NULL CHECK (IS_DELETED IN (0,1))  --  逻辑删除;0：未删除，1：已删除
);

COMMENT ON TABLE FIXEDWAGE IS '固定工资表';
COMMENT ON COLUMN FIXEDWAGE.FIXEDWAGE_ID IS '固定工资编号';
COMMENT ON COLUMN FIXEDWAGE.FIXEDWAGE_PERIODMONEY IS '试用期基本工资';
COMMENT ON COLUMN FIXEDWAGE.STAFF_ID IS '员工编号';
COMMENT ON COLUMN FIXEDWAGE.FIXEDWAGE_OFFICIALMONEY IS '正式期基本工资';
COMMENT ON COLUMN FIXEDWAGE.FIXEDWAGE_PERIODPOSTMONEY IS '试用期岗位工资';
COMMENT ON COLUMN FIXEDWAGE.FIXEDWAGE_OFFLCIALPOSTMONEY IS '正式期岗位工资';
COMMENT ON COLUMN FIXEDWAGE.FIXEDWAGE_REMARK IS '备注';
COMMENT ON COLUMN FIXEDWAGE.CREATED_TIME IS '创建时间';
COMMENT ON COLUMN FIXEDWAGE.UPDATED_TIME IS '修改时间';
COMMENT ON COLUMN FIXEDWAGE.REVISION IS '乐观锁';
COMMENT ON COLUMN FIXEDWAGE.IS_DELETED IS '逻辑删除;0：未删除，1：已删除';


/*创建固定工资自增序列*/
CREATE SEQUENCE FIXEDWAGE_ID
  --最小值
MINVALUE 1     
 --不设置最大值
NOMAXVALUE      
  --从1开始计数
START WITH 1   
 --每次加1
INCREMENT BY 1 
 --一直累加，不循环
NOCYCLE 
--不建缓冲区
NOCACHE;


-- 创建工资表
CREATE TABLE WAG(
    WAG_ID NUMBER(10) NOT NULL PRIMARY KEY,   --  工资编号
    FIXEDWAGE_ID NUMBER(10,2) NOT NULL,  --  固定工资编号
    STAFF_ID NUMBER(10) NOT NULL,  --  员工编号
    DEPT_ID NUMBER(10) NOT NULL,  --  部门编号
    ATTENDANCE_SHEET_ID NUMBER(10) NOT NULL,  --  考勤编号
		INS_ARCHIVE_ID number(10) ,-- 参保归档编号
    OVERTIMEASK_ID NUMBER(10) NOT NULL,  --  加班编号
    CREATED_TIME DATE NOT NULL,  --  创建时间
    UPDATED_TIME DATE NOT NULL,  --  修改时间
    REVISION NUMBER(10) DEFAULT  1 NOT NULL, --  乐观锁
		IS_DELETED NUMBER(10) DEFAULT  0 NOT NULL CHECK (IS_DELETED IN (0,1))  --  逻辑删除;0：未删除，1：已删除
);

COMMENT ON TABLE WAG IS '工资表';
COMMENT ON COLUMN WAG.WAG_ID IS '工资编号';
COMMENT ON COLUMN WAG.FIXEDWAGE_ID IS '固定工资编号';
COMMENT ON COLUMN WAG.STAFF_ID IS '员工编号';
COMMENT ON COLUMN WAG.DEPT_ID IS '部门编号';
COMMENT ON COLUMN WAG.INS_ARCHIVE_ID IS '参保归档编号';
COMMENT ON COLUMN WAG.ATTENDANCE_SHEET_ID IS '考勤编号';
COMMENT ON COLUMN WAG.OVERTIMEASK_ID IS '加班编号';
COMMENT ON COLUMN WAG.CREATED_TIME IS '创建时间';
COMMENT ON COLUMN WAG.UPDATED_TIME IS '修改时间';
COMMENT ON COLUMN WAG.REVISION IS '乐观锁';
COMMENT ON COLUMN WAG.IS_DELETED IS '逻辑删除;0：未删除，1：已删除';

/*创建工资自增序列*/
CREATE SEQUENCE WAG_ID
  --最小值
MINVALUE 1     
 --不设置最大值
NOMAXVALUE      
  --从1开始计数
START WITH 1   
 --每次加1
INCREMENT BY 1 
 --一直累加，不循环
NOCYCLE 
--不建缓冲区
NOCACHE;






-- 创建工资归档表
CREATE TABLE MONEYPIGEONHOLE(
    MONEYPIGEONHOLE_ID NUMBER(10) NOT NULL PRIMARY KEY,   --   工资归档编号
    DEPT_name varchar2(20) not null,  -- 部门名称  
    moneypigeonhole_askperson number(10),  --  计薪人数
    moneypigeonhole_salary number(10,2) NOT NULL,   --  应发工资
    moneypigeonhole_payrollsalary number(10,2) NOT NULL,  --  实发工资
    moneypigeonhole_firmpayment number(10,2) NOT NULL,  --  公司缴纳
    moneypigeonhole_staffcost number(10,2) NOT NULL,  --  员工成本   
    moneypigeonhole_state number(10) DEFAULT  0 NOT NULL check (moneypigeonhole_state in (0,1)),  --状态;0：未归档，1：已归档
    STAFF_NAME  VARCHAR2(20) NOT NULL, -- 员工姓名
    moneypigeonhole_post varchar2(20) not null,-- 职位
    moneypigeonhole_basepay NUMBER(10,2) DEFAULT 0 NOT NULL,  -- 基本工资
    workdayovertimepay  NUMBER(10,2) DEFAULT 0 NOT NULL,  -- 工作日加班工资
    dayoffovertimepay  NUMBER(10,2) DEFAULT 0 NOT NULL, -- 休息日加班工资
    holidayovertimepay NUMBER(10,2) DEFAULT 0 NOT NULL, -- 节假日加班工资
    totalwage NUMBER(10,2) DEFAULT 0 NOT NULL,  -- 工资合计
		travelwage NUMBER(10,2) not null,-- 出差工资
    MONEYPIGEONHOLE_late  NUMBER(10,2) DEFAULT 0 NOT NULL, -- 迟到
    MONEYPIGEONHOLE_leavearly  NUMBER(10,2) DEFAULT 0 NOT NULL,  -- 早退
    MONEYPIGEONHOLE_notsignin   NUMBER(10,2) DEFAULT 0, -- 未签到
    MONEYPIGEONHOLE_notsignback   NUMBER(10,2) DEFAULT 0, -- 未签退
    absenteism  NUMBER(10,2) DEFAULT 0 NOT NULL, -- 旷工
    cusualleave  varchar2(10), --  事假
    sickleave  varchar2(10), --  病假
    PERSONAGE_ACCUMULATION NUMBER(10,2) DEFAULT 0 NOT NULL,  -- 个人缴公积金
    PERSONAGE_SOCIAL NUMBER(10,2) DEFAULT 0 NOT NULL,  -- 个人缴社保
    COMPANY_SOCIAL NUMBER(10,2) DEFAULT 0 NOT NULL,  -- 公司缴社保
    COMPANY_ACCUMULATION NUMBER(10,2) DEFAULT 0 NOT NULL,  -- 公司缴公积金    
    MONEYPIGEONHOLE_DATE DATE ,  --  日期
    CREATED_TIME DATE NOT NULL,  --  创建时间
    UPDATED_TIME DATE NOT NULL,   --  修改时间
    IS_DELETED NUMBER(10) DEFAULT  0 NOT NULL CHECK (IS_DELETED IN (0,1)),  --  逻辑删除;0：未删除，1：已删除
    REVISION NUMBER(10) DEFAULT  1 NOT NULL   --  乐观锁
);

COMMENT ON TABLE MONEYPIGEONHOLE IS '工资归档表';
COMMENT ON COLUMN MONEYPIGEONHOLE.MONEYPIGEONHOLE_ID IS '工资归档编号';
COMMENT ON COLUMN MONEYPIGEONHOLE.DEPT_name IS '工资归档编号';
COMMENT ON COLUMN moneypigeonhole.moneypigeonhole_askperson IS '计薪人数';
COMMENT ON COLUMN moneypigeonhole.moneypigeonhole_salary IS '应发工资';
COMMENT ON COLUMN moneypigeonhole.moneypigeonhole_payrollsalary IS '实发工资';
COMMENT ON COLUMN moneypigeonhole.moneypigeonhole_firmpayment IS '公司缴纳';
COMMENT ON COLUMN MONEYPIGEONHOLE.MONEYPIGEONHOLE_staffcost IS '员工成本';
COMMENT ON COLUMN MONEYPIGEONHOLE.MONEYPIGEONHOLE_state IS '状态;0：未归档，1：已归档';
COMMENT ON COLUMN MONEYPIGEONHOLE.STAFF_NAME IS '员工姓名';
COMMENT ON COLUMN MONEYPIGEONHOLE. moneypigeonhole_post IS '职位';
COMMENT ON COLUMN MONEYPIGEONHOLE. moneypigeonhole_basepay IS '基本工资';
COMMENT ON COLUMN MONEYPIGEONHOLE.  workdayovertimepay IS '工作日加班工资';
COMMENT ON COLUMN MONEYPIGEONHOLE. dayoffovertimepay IS '休假日加班工资';
COMMENT ON COLUMN MONEYPIGEONHOLE. holidayovertimepay IS '节假日加班工资';
COMMENT ON COLUMN MONEYPIGEONHOLE. totalwage IS '工资合计';
COMMENT ON COLUMN MONEYPIGEONHOLE. MONEYPIGEONHOLE_late IS '迟到';
COMMENT ON COLUMN MONEYPIGEONHOLE. MONEYPIGEONHOLE_leavearly IS '早退';
COMMENT ON COLUMN MONEYPIGEONHOLE. MONEYPIGEONHOLE_notsignin IS '未签到';
COMMENT ON COLUMN MONEYPIGEONHOLE. MONEYPIGEONHOLE_notsignback IS '未签退';
COMMENT ON COLUMN MONEYPIGEONHOLE.  absenteism IS '旷工';
COMMENT ON COLUMN MONEYPIGEONHOLE. cusualleave IS '事假';
COMMENT ON COLUMN MONEYPIGEONHOLE. sickleave IS '病假';
COMMENT ON COLUMN MONEYPIGEONHOLE. PERSONAGE_ACCUMULATION IS '个人缴公积金';
COMMENT ON COLUMN MONEYPIGEONHOLE.  PERSONAGE_SOCIAL IS '个人缴社保';
COMMENT ON COLUMN MONEYPIGEONHOLE.COMPANY_SOCIAL IS '公司缴社保';
COMMENT ON COLUMN MONEYPIGEONHOLE.COMPANY_ACCUMULATION IS '公司缴公积金';
COMMENT ON COLUMN MONEYPIGEONHOLE.MONEYPIGEONHOLE_DATE IS '日期';
COMMENT ON COLUMN FIXEDWAGE.CREATED_TIME IS '创建时间';
COMMENT ON COLUMN MONEYPIGEONHOLE.UPDATED_TIME IS '修改时间';
COMMENT ON COLUMN MONEYPIGEONHOLE.REVISION IS '乐观锁';
COMMENT ON COLUMN MONEYPIGEONHOLE.IS_DELETED IS '逻辑删除;0：未删除，1：已删除';

/*创建工资归档自增序列*/
CREATE SEQUENCE MONEYPIGEONHOLE_ID
  --最小值
MINVALUE 1     
 --不设置最大值
NOMAXVALUE      
  --从1开始计数
START WITH 1   
 --每次加1
INCREMENT BY 1 
 --一直累加，不循环
NOCYCLE 
--不建缓冲区
NOCACHE;



-- 创建考勤扣款方案表
CREATE TABLE ATTENDANDCE(
    ATTENDANDCE_ID NUMBER(10) NOT NULL PRIMARY KEY,  --  考勤扣款方案编号
    ATTENDANDCE_LITEMONEY NUMBER(10,2) DEFAULT 0 NOT NULL,  -- 迟到一次金额
		ATTENDANDCE_NAME VARCHAR2(50) not null,--考勤方案名称
    ATTENDANDCE_LEAVEMONEY NUMBER(10,2) DEFAULT 0 NOT NULL,  --  早退一次金额
    ATTENDANDCE_DIDNOTMONEY NUMBER(10,2) DEFAULT 0 NOT NULL, --  未签到一次金额
    ATTENDANDCE_DIDBACKMONEY NUMBER(10,2) DEFAULT 0 NOT NULL,  --  未签退一次金额
    ATTENDANDCE_ABSCNTMONEY NUMBER(10,2) DEFAULT 0 NOT NULL,   --  旷工一天金额
    ATTENDANDCE_STATE NUMBER(10) DEFAULT  0 NOT NULL CHECK (ATTENDANDCE_STATE IN (0,1)),  --  状态;0：启用，1：禁用
    ATTENDANDCE_REMARK VARCHAR2(1000),  --  备注
		DEPT_NAME VARCHAR2(200), -- 适用对象jiade
    REVISION NUMBER(10) DEFAULT  1 NOT NULL,  -- 乐观锁
   CREATED_TIME DATE NOT NULL,  --  创建时间
   IS_DELETED NUMBER(10) DEFAULT  0 NOT NULL CHECK (IS_DELETED IN (0,1)),  --  逻辑删除;0：未删除，1：已删除
    UPDATED_TIME DATE NOT NULL  --  修改时间
);

COMMENT ON TABLE ATTENDANDCE IS '考勤扣款方案表';
COMMENT ON COLUMN ATTENDANDCE.ATTENDANDCE_ID IS '考勤扣款方案编号';
COMMENT ON COLUMN ATTENDANDCE.ATTENDANDCE_LITEMONEY IS '迟到一次金额';
COMMENT ON COLUMN ATTENDANDCE.ATTENDANDCE_LEAVEMONEY IS '早退一次金额';
COMMENT ON COLUMN ATTENDANDCE.ATTENDANDCE_DIDNOTMONEY IS '未签到一次金额';
COMMENT ON COLUMN ATTENDANDCE.ATTENDANDCE_DIDBACKMONEY IS '未签退一次金额';
COMMENT ON COLUMN ATTENDANDCE.ATTENDANDCE_ABSCNTMONEY IS '旷工一天金额';
COMMENT ON COLUMN ATTENDANDCE.ATTENDANDCE_STATE IS '状态;0：启用，1：禁用';
COMMENT ON COLUMN ATTENDANDCE.ATTENDANDCE_REMARK IS '备注';
COMMENT ON COLUMN ATTENDANDCE.REVISION IS '乐观锁';
COMMENT ON COLUMN ATTENDANDCE.CREATED_TIME IS '创建时间';
COMMENT ON COLUMN ATTENDANDCE.UPDATED_TIME IS '修改时间';
COMMENT ON COLUMN ATTENDANDCE.IS_DELETED IS '逻辑删除;0：未删除，1：已删除';



/*创建考勤扣款方案自增序列*/
CREATE SEQUENCE ATTENDANDCE_ID
  --最小值
MINVALUE 1     
 --不设置最大值
NOMAXVALUE      
  --从1开始计数
START WITH 1   
 --每次加1
INCREMENT BY 1 
 --一直累加，不循环
NOCYCLE 
--不建缓冲区
NOCACHE;


-- 创建考勤适用对象表
CREATE TABLE CHECKAPPLY(
    CHECKAPPLY_ID NUMBER(10) NOT NULL PRIMARY KEY,  --  考勤适用对象编号
    ATTENDANDCE_ID NUMBER(10) NOT NULL,  --  考勤扣款方案编号
    DEPT_ID NUMBER(10) NOT NULL,  --  部门编号
    CREATED_TIME DATE NOT NULL,  --  创建时间
    UPDATED_TIME DATE NOT NULL,  --  修改时间
		IS_DELETED NUMBER(10) DEFAULT  0 NOT NULL CHECK (IS_DELETED IN (0,1)),  --  逻辑删除;0：未删除，1：已删除
    REVISION NUMBER(10) DEFAULT  1 NOT NULL --  乐观锁
);

COMMENT ON TABLE CHECKAPPLY IS '考勤适用对象表';
COMMENT ON COLUMN CHECKAPPLY.CHECKAPPLY_ID IS '考勤适用对象编号';
COMMENT ON COLUMN CHECKAPPLY.ATTENDANDCE_ID IS '考勤扣款方案编号';
COMMENT ON COLUMN CHECKAPPLY.DEPT_ID IS '部门编号';
COMMENT ON COLUMN CHECKAPPLY.CREATED_TIME IS '创建时间';
COMMENT ON COLUMN CHECKAPPLY.UPDATED_TIME IS '修改时间';
COMMENT ON COLUMN CHECKAPPLY.REVISION IS '乐观锁';
COMMENT ON COLUMN CHECKAPPLY.IS_DELETED IS '逻辑删除;0：未删除，1：已删除';

/*创建考勤适用对象自增序列*/
CREATE SEQUENCE CHECKAPPLY_ID
  --最小值
MINVALUE 1     
 --不设置最大值
NOMAXVALUE      
  --从1开始计数
START WITH 1   
 --每次加1
INCREMENT BY 1 
 --一直累加，不循环
NOCYCLE 
--不建缓冲区
NOCACHE;
	
		
-- 创建出差方案表
CREATE TABLE BUSINESS(
    BUSINESS_ID NUMBER(10) NOT NULL PRIMARY KEY,  --  出差方案编号
   TRAVEL_ID NUMBER(10),  --  出差编号
    BUSINESS_NAME VARCHAR2(100) NOT NULL,  --  出差方案名称
    BUSINESS_ONEMONEY NUMBER(10,2) DEFAULT 0 NOT NULL,  -- 出差一天金额
    BUSINESS_STATE NUMBER(10) DEFAULT 0,  --  状态
    BUSINESS_REMARK VARCHAR2(1000),  --  备注
		DEPT_NAME VARCHAR2(200), -- 适用对象jiade
    CREATED_TIME DATE NOT NULL,  --  创建时间
    UPDATED_TIME DATE NOT NULL,  --  修改时间
    IS_DELETED NUMBER(10) DEFAULT  0 NOT NULL,  --  逻辑删除;0：未删除，1：已删除
    REVISION NUMBER(10) DEFAULT  1 NOT NULL   --  乐观锁
);

COMMENT ON TABLE BUSINESS IS '出差方案表';
COMMENT ON COLUMN BUSINESS.BUSINESS_ID IS '出差方案编号';
COMMENT ON COLUMN BUSINESS.TRAVEL_ID IS '出差编号';
COMMENT ON COLUMN BUSINESS.BUSINESS_NAME IS '出差方案名称';
COMMENT ON COLUMN BUSINESS.BUSINESS_ONEMONEY IS '出差一天金额';
COMMENT ON COLUMN BUSINESS.BUSINESS_STATE IS '状态';
COMMENT ON COLUMN BUSINESS.BUSINESS_REMARK IS '备注';
COMMENT ON COLUMN BUSINESS.CREATED_TIME IS '创建时间';
COMMENT ON COLUMN BUSINESS.UPDATED_TIME IS '修改时间';
COMMENT ON COLUMN BUSINESS.IS_DELETED IS '逻辑删除;0：未删除，1：已删除';
COMMENT ON COLUMN BUSINESS.REVISION IS '乐观锁';


/*创建出差方案自增序列*/
CREATE SEQUENCE BUSINESS_ID
  --最小值
MINVALUE 1     
 --不设置最大值
NOMAXVALUE      
  --从1开始计数
START WITH 1   
 --每次加1
INCREMENT BY 1 
 --一直累加，不循环
NOCYCLE 
--不建缓冲区
NOCACHE;


--创建部门表

CREATE TABLE DEPT(
    DEPT_ID NUMBER(10)  PRIMARY KEY NOT NULL, --部门编号
    DEPT_STATE NUMBER(10) DEFAULT 0 CHECK(DEPT_STATE IN (0,1)) NOT NULL, --状态 （0，启用，1，禁用）
    DEPT_NAME VARCHAR2(90) NOT NULL, --部门名称
    STAFF_ID NUMBER(10), --部门负责人编号
    CREATED_TIME DATE NOT NULL,-- 创建时间
    UPDATED_TIME DATE NOT NULL,-- 修改时间
    REVISION NUMBER(10) DEFAULT 1 NOT NULL,-- 乐观锁
		IS_DELETED NUMBER(10) DEFAULT  0 NOT NULL  --  逻辑删除;0：未删除，1：已删除
);

COMMENT ON TABLE DEPT IS '部门表';
COMMENT ON COLUMN DEPT.DEPT_ID IS '部门编号';
COMMENT ON COLUMN DEPT.DEPT_STATE IS '状态;0：启用  1：禁用';
COMMENT ON COLUMN DEPT.DEPT_NAME IS '部门名称';
COMMENT ON COLUMN DEPT.STAFF_ID IS '部门负责人;提供ID到员工表锁定具体的人';
COMMENT ON COLUMN DEPT.REVISION IS '乐观锁';
COMMENT ON COLUMN DEPT.CREATED_TIME IS '创建时间';
COMMENT ON COLUMN DEPT.UPDATED_TIME IS '修改时间';
COMMENT ON COLUMN DEPT.IS_DELETED IS '逻辑删除;0：未删除，1：已删除';


--创建自增序列
CREATE SEQUENCE DEPT_ID
  --最小值
MINVALUE 1     
 --不设置最大值
NOMAXVALUE      
  --从1开始计数
START WITH 1   
 --每次加1
INCREMENT BY 1 
 --一直累加，不循环
NOCYCLE 
--不建缓冲区
NOCACHE;


--创建部门修改记录表
CREATE TABLE DEPTCLA(
    DEPTCLA_ID NUMBER(10) PRIMARY KEY NOT NULL, --记录编号
    ALTER_A_NAME VARCHAR2(90) NOT NULL, --修改前名称
    ALTER_B_NAME VARCHAR2(90) NOT NULL, --修改后名称
    REVISION NUMBER(10) DEFAULT  1 NOT NULL, --乐观锁
    CREATED_BY VARCHAR2(32) NOT NULL, --修改前负责人
    UPDATED_BY VARCHAR2(32) NOT NULL, --修改后负责人
    CREATED_TIME DATE NOT NULL,-- 创建时间
    UPDATED_TIME DATE NOT NULL,-- 修改时间
		IS_DELETED NUMBER(10) DEFAULT  0 NOT NULL  --  逻辑删除;0：未删除，1：已删除
);

COMMENT ON TABLE DEPTCLA IS '部门修改记录表';
COMMENT ON COLUMN DEPTCLA.DEPTCLA_ID IS '记录编号';
COMMENT ON COLUMN DEPTCLA.ALTER_A_NAME IS '修改前名称';
COMMENT ON COLUMN DEPTCLA.ALTER_B_NAME IS '修改后名称';
COMMENT ON COLUMN DEPTCLA.REVISION IS '乐观锁';
COMMENT ON COLUMN DEPTCLA.CREATED_BY IS '修改前负责人编号;通过ID搜索员工表';
COMMENT ON COLUMN DEPTCLA.UPDATED_BY IS '修改后负责人编号;通过ID搜索员工表';
COMMENT ON COLUMN DEPTCLA.CREATED_TIME IS '创建时间';
COMMENT ON COLUMN DEPTCLA.UPDATED_TIME IS '更新时间';
COMMENT ON COLUMN DEPTCLA.IS_DELETED IS '逻辑删除;0：未删除，1：已删除';

CREATE SEQUENCE DEPTCLA_ID
  --最小值
MINVALUE 1     
 --不设置最大值
NOMAXVALUE      
  --从1开始计数
START WITH 1   
 --每次加1
INCREMENT BY 1 
 --一直累加，不循环
NOCYCLE 
--不建缓冲区
NOCACHE; 

--创建部门职位表
CREATE TABLE DEPT_POST(
    DEPT_POST_ID NUMBER(10) PRIMARY KEY NOT NULL, --部门职位编号
    DEPT_ID   NUMBER(10) NOT NULL, --部门编号
    POST_NAME VARCHAR2(20) NOT NULL, --职位名称
    REVISION NUMBER(10) DEFAULT  1 NOT NULL, --乐观锁
    CREATED_TIME DATE NOT NULL,-- 创建时间
    UPDATED_TIME DATE NOT NULL,-- 修改时间
		IS_DELETED NUMBER(10) DEFAULT  0 NOT NULL  --  逻辑删除;0：未删除，1：已删除
);

COMMENT ON TABLE DEPT_POST IS '部门职位表';
COMMENT ON COLUMN DEPT_POST.DEPT_POST_ID IS '部门职位编号';
COMMENT ON COLUMN DEPT_POST.DEPT_ID IS '部门编号';
COMMENT ON COLUMN DEPT_POST.POST_NAME IS '职位名称';
COMMENT ON COLUMN DEPT_POST.REVISION IS '乐观锁';
COMMENT ON COLUMN DEPT_POST.CREATED_TIME IS '创建时间';
COMMENT ON COLUMN DEPT_POST.UPDATED_TIME IS '修改时间';
COMMENT ON COLUMN DEPT_POST.IS_DELETED IS '逻辑删除;0：未删除，1：已删除';

--创建自增序列
CREATE SEQUENCE DEPT_POST_ID
  --最小值
MINVALUE 1     
 --不设置最大值
NOMAXVALUE      
  --从1开始计数
START WITH 1   
 --每次加1
INCREMENT BY 1 
 --一直累加，不循环
NOCYCLE 
--不建缓冲区
NOCACHE; 














