server:
  port: 80
#开启服务降级fegin.hystrix
feign:
  hystrix:
    enabled: true
  httpclient:
    connection-timeout: 10000

##配置spring security 账号密码
#spring:
#  security:
#    user:
#      name: admin
#      password: admin

# JWT配置
jwt:
  # 密匙KEY
  secret: JWTSecret
  # HeaderKEY
  header: jwtAuth
  # 过期时间毫秒
  expire: 100000

#hystrix熔断超时配置
hystrix:
  command:
    default:  #default全局有效，service id指定应用有效
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制,为true,则超时作为熔断根据
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 80000 #断路器超时时间，默认1000ms


# 远程调用超时时间
ribbon:
  OkToRetryOnAllOperations: false #对所有操作请求都进行重试,默认false
  ReadTimeout: 80000   #负载均衡超时时间，默认值5000
  ConnectTimeout: 80000 #ribbon请求连接的超时时间，默认值2000
  MaxAutoRetries: 0     #对当前实例的重试次数，默认0
  MaxAutoRetriesNextServer: 1 #对切换实例的重试次数，默认1

#Redis配置
#spring:
#  redis:
#    database: 0 # Redis 数据库索引（默认为 0）
#    host: 127.0.0.1 # Redis 服务器地址
#    port: 6379 # Redis 服务器连接端口
#    password: 123456  # Redis 服务器连接密码（默认为空）
#    lettuce:
#      pool:
#        max-active: 8 # 连接池最大连接数（使用负值表示没有限制） 默认 8
#        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
#        max-idle: 8 # 连接池中的最大空闲连接 默认 8
#        min-idle: 0 # 连接池中的最小空闲连接 默认 0
#Eureka配置
eureka:
  client:
    register-with-eureka: false #不向Eureka注册自己
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/