server:
  port: 80
#开启服务降级fegin.hystrix
feign:
  hystrix:
    enabled: true
#hystrix熔断超时配置
hystrix:
  command:
    default:
      execution:
        #开启超时配置(默认为开启)
        timeout:
          enabled: true
        #设置超时时间
        isolation:
          thread:
            timeoutInMilliseconds: 4000
#Eureka配置
eureka:
  client:
    register-with-eureka: false #不向Eureka注册自己
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/