package com.trkj.framework.mybatisplus.mapper;

import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.baomidou.mybatisplus.core.metadata.IPage;
import com.baomidou.mybatisplus.core.toolkit.Constants;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import com.trkj.framework.vo.WageTableVo;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

@Mapper
public interface WageTableMapper extends BaseMapper<WageTableVo> {

    /**
     * 查询工资表
     * @param page
     * @param queryWrapper
     * @return
     */
    @Select("SELECT DISTINCT s.STAFF_NAME,f.FIXEDWAGE_ID,f.FIXEDWAGE_PERIODMONEY,f.FIXEDWAGE_OFFICIALMONEY,f.FIXEDWAGE_PERIODPOSTMONEY,f.FIXEDWAGE_OFFLCIALPOSTMONEY,f.FIXEDWAGE_REMARK,w.WORKSCHEME_ID,w.WORKSCHEME_NAME,w.WORKSCHEME_HOLIDAYRATIO,w.WORKSCHEME_DAYOFFRATIO,w.WORKSCHEME_WORKRATIO,w.WORKSCHEME_STATE,w.WORKSCHEME_REMARK,a.ATTENDANDCE_ID,a.ATTENDANDCE_LITEMONEY,a.ATTENDANDCE_NAME,a.ATTENDANDCE_LEAVEMONEY,a.ATTENDANDCE_DIDNOTMONEY,a.ATTENDANDCE_DIDBACKMONEY,a.ATTENDANDCE_ABSCNTMONEY,a.ATTENDANDCE_STATE,a.ATTENDANDCE_REMARK,b.BUSINESS_ID,b.BUSINESS_NAME,b.BUSINESS_ONEMONEY,b.BUSINESS_STATE,b.BUSINESS_REMARK,o.OVERTIMEASK_ID,o.AUDITFLOW_ID,o.OVERTIMEASK_TYPE,o.OVERTIMEASK_MATTER,o.OVERTIMEASK_REMARKS,o.OVERTIMEASK_S_DATE,o.OVERTIMEASK_E_DATE,o.OVERTIMEASK_TOTAL_DATE,o.OVERTIMASK_ACTUAL_TIME,o.OVERTIMASK_ACTUAL_OVERTIME,o.OVERTIMASK_ACTUAL_TOKINAGA,o.OVERTIMEASK_STATE,o.OVERTIMEASK_CONDITION,ar.ARCHIVE_ID,ar.ARCHIVE_NAME,ar.NORMAL_FREQUENCY,ar.LATE_FREQUENCY,ar.ABSENTEEISM_FREQUENCY,ar.LEAVE_EARLY_FREQUENCY,ar.PRESENT,t.TRAVEL_ID,t.TRAVEL_PLACE,t.TRAVEL_MATTER,t.TRAVEL_S_DATE,t.TRAVEL_E_DATE,t.TRAVEL_TOTAL_DATE,t.TRAVEL_ACTUAL_TIME,t.TRAVEL_ACTUAL_OVERTIME,t.TRAVEL_ACTUAL_TOKINAGA,t.TRAVEL_STATE,t.TRAVEL_CONDITION,i.*,d.DEPT_NAME,p.POST_NAME FROM STAFF s LEFT JOIN FIXEDWAGE f on f.STAFF_ID=s.STAFF_ID LEFT JOIN DEPT d on d.DEPT_ID=s.DEPT_ID LEFT JOIN DEPT_POST p on p.DEPT_POST_ID=s.DEPT_POST_ID LEFT JOIN WORKSCHEME w on w.DEPT_NAME=d.DEPT_NAME LEFT JOIN ATTENDANDCE a on a.DEPT_NAME=d.DEPT_NAME LEFT JOIN BUSINESS b on b.DEPT_NAME=d.DEPT_NAME LEFT JOIN OVERTIMEASK o on o.STAFF_NAME=s.STAFF_NAME LEFT JOIN ARCHIVE ar on ar.STAFF_NAME=s.STAFF_NAME LEFT JOIN TRAVEL t on t.TRAVEL_ID=b.TRAVEL_ID LEFT JOIN INSURED_ARCHIVE i on i.INS_ARCHIVE_STAFF_NAME=s.STAFF_NAME ${ew.customSqlSegment}")
    IPage<WageTableVo> selectWage(Page<WageTableVo> page, @Param(Constants.WRAPPER)QueryWrapper<WageTableVo> queryWrapper);
}
