server:
  port: 8009
  #连接池配置
  servlet:
    context-path: /provider
feign:
  hystrix:
    enabled: true
    #局部配置
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
spring:
  profiles:
    active: dev